### ISSUE TITLE
Please provide option to set inventory file location 

### ISSUE THREAD

**Issue by skommala** [oracle/weblogic-image-tool#103]
We have the need to provide different inventory location and group in the inventory file. Right now imagetool has hard coded inventory location. 

It would be really helpful if the variable is configurable when installing 12.2.1.3 bundle and patches.

**Comment by jshum2479** [comment]
This requires several things:
1. User-specified location pointer file with contents
inventory_loc=/u01/app/oraInventory
inst_group=oinstall
2. Where the user wants to put this pointer file (e.g.  --inventoryPointerInstallPath )
3. The tool needs to make sure the inventory_loc/** are copied to the final layer and also the location file and path are copied to the final layer.

**Comment by ddsharpe** [comment]
Fixed #107
