### ISSUE TITLE
image tool domain creation with WDT tool failing -->/u01/domains/base_domain is not a directory>

### ISSUE THREAD

**Issue by MaheshwarReddyGade** [oracle/weblogic-image-tool#112]
Step 35/49 : COPY --chown=oracle:oinstall domain.properties /u01/wdt/models/
 ---> d6051a5eba89
Step 36/49 : RUN unzip -q /tmp/imagetool/$WDT_PKG -d /u01/wdt         && cd /u01/wdt/weblogic-deploy/bin         && ./createDomain.sh         -oracle_home /u01/oracle         -domain_home /u01/domains/base_domain         -domain_type WLS         -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip
 ---> Running in d32f0e584d30
JDK version is 1.8.0_211-b12
JAVA_HOME = /u01/jdk
WLST_EXT_CLASSPATH = /u01/wdt/weblogic-deploy/lib/weblogic-deploy-core.jar
CLASSPATH =
WLST_PROPERTIES = -Djava.util.logging.config.class=oracle.weblogic.deploy.logging.WLSDeployLoggingConfig -Dcom.oracle.cie.script.throwException=true  -Djava.security.egd=file:/dev/./urandom
/u01/oracle/oracle_common/common/bin/wlst.sh /u01/wdt/weblogic-deploy/lib/python/create.py -oracle_home /u01/oracle -domain_home /u01/domains/base_domain -domain_type WLS -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip
The createDomain program will write its log to /u01/wdt/weblogic-deploy/logs/createDomain.log

Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Dec 28, 2019 4:06:36 PM> <SEVERE> <create> <main> <WLSDPLY-20008> <createDomain argument processing failed: Supplied Domain Home directory /u01/domains/base_domain was not valid: Directory /u01/domains/base_domain is not a directory>

createDomain.sh failed due to a parameter validation error
Removing intermediate container d32f0e584d30
[SEVERE ] Response code: -1, message: docker command failed with error: The command '/bin/sh -c unzip -q /tmp/imagetool/$WDT_PKG -d /u01/wdt         && cd /u01/wdt/weblogic-deploy/bin         && ./createDomain.sh         -oracle_home /u01/oracle         -domain_home /u01/domains/base_domain         -domain_type WLS         -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip' returned a non-zero code: 98

**Comment by MaheshwarReddyGade** [comment]
Command used:
 imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u211 --wdtModel=/u01/install/software/sample.yaml --wdtVariables=/u01/oracle/properties/domain.properties --wdtArchive /u01/install/software/archive.zip --wdtVersion 1.6.2 --chown oracle:oinstall --user maheswar.gade@datavail.com --password Arvpg2831k@ 


with parameter --wdtDomainHome /u01/oracle/Middleware/domains/asr_domain also failing .. not sure why ..

**Comment by MaheshwarReddyGade** [comment]
imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u211 --wdtModel=/u01/install/software/sample.yaml --wdtVariables=/u01/oracle/properties/domain.properties --wdtArchive /u01/install/software/archive.zip --wdtVersion 1.6.2 --chown oracle:oinstall --user maheswar.gade@xxxxx.com --password xxxxxxx

with parameter wdtDomainHome setting to diff directory also failing ..

**Comment by mriccell** [comment]
I tried a similar command using my own WDT model and Archive but did not experience any issues.  This is the command I used: imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u221 --wdtModel=/Users/mriccell/HOL/CI-CD/weblogic-cicd-k8s/DiscoverDomain-v1.yaml --wdtVariables=/Users/mriccell/HOL/CI-CD/weblogic-cicd-k8s/domain.properties --wdtArchive /Users/mriccell/HOL/CI-CD/weblogic-cicd-k8s/DiscoveredDemoDomain.zip  --wdtDomainHome=/u01/oracle/user_projects/domains/onprem-domain --wdtVersion 1.6.2 --chown oracle:oinstall --user monica.riccelli@oracle.com --password $MYPWD.  
I set --wdtDomainHome=/u01/oracle/user_projects/domains/onprem-domain where onprem-domain is the name of my DOMAIN HOME.

**Comment by jshum2479** [comment]
@MaheshwarReddyGade  What version of docker you are using ?

If you add --dryRun to the imagetool command line parameters, you should see a line similar to this for creating the directory of the domain in the dockerfile 

   mkdir -p $(dirname /u01/domains/base_domain) 

Make sure you have the --wdtDomainHome set.   

docker version will tell us which version of docker you are using (also, please let us know which platform you are on).

**Comment by MaheshwarReddyGade** [comment]
@jshum2479  @mriccell  Thanks a lot ..

My docker/Platform details:

Client: Docker Engine - Community
 Version:           19.03.1-ol
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        ead9442
 Built:             Wed Sep 11 06:40:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

I see mkdir -p $(dirname /u01/domains/base_domain) in my Docker file .. Not sure why it says domain directory does not exist .. 

with additional build command also i tried .. 
--additionalBuildCommands=/u01/install/projects/tools/imagetool/bin/buildargs

[oracle@ebsasserter ebsasserter_ebsdb]$ cat /u01/install/projects/tools/imagetool/bin/buildargs
[after-fmw-install]
    RUN  mkdir -p /u01/oracle/Middleware/domains/asr_domain/
        COPY --chown=oracle:oinstall config.xml /u01/oracle/Middleware/domains/asr_domain/
[oracle@ebsasserter ebsasserter_ebsdb]$



cd /u01/install/projects/tools/imagetool/bin
. ./setup.sh
export JAVA_HOME=/u01/install/software/jdk1.8.0_211
export PATH=$JAVA_HOME/bin:$PATH
imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u211 --wdtModel=/u01/install/software/sample.yaml --wdtVariables=/u01/oracle/properties/domain.properties --wdtArchive /u01/install/software/archive.zip --wdtDomainHome /u01/oracle/Middleware/domains/asr_domain/ --wdtVersion 1.6.2 --chown oracle:oinstall --additionalBuildCommands=/u01/install/projects/tools/imagetool/bin/buildargs --user maheswar.gade@datavail.com --password Arvpg2831k@



After this .. it says config.xml file does not exist inside domain home.  I'm not sure where i'm going wrong .. 

Here i'm attaching files for your reference ..  Kindly check and help.
archive.zip uploaded which i'm using ..

domain.properties uploaded 
[domain.properties.log](https://github.com/oracle/weblogic-image-tool/files/4043929/domain.properties.log)

[archive.zip](https://github.com/oracle/weblogic-image-tool/files/4043924/archive.zip)

sanple.yaml file uploaded .. 
[sample.yaml.log](https://github.com/oracle/weblogic-image-tool/files/4043927/sample.yaml.log)

**Comment by MaheshwarReddyGade** [comment]
Error i'm getting :
Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

####<Jan 10, 2020 2:49:58 PM> <SEVERE> <create> <main> <WLSDPLY-20008> <createDomain argument processing failed: Supplied Domain Home /u01/oracle/Middleware/domains/asr_domain did not contain a valid config.xml file at /u01/oracle/Middleware/domains/asr_domain/config/config.xml: File /u01/oracle/Middleware/domains/asr_domain/config/config.xml does not exist>

createDomain.sh failed due to a parameter validation error
Removing intermediate container a85ab54b2fd5
[SEVERE ] Response code: -1, message: docker command failed with error: The command '/bin/sh -c unzip -q /tmp/imagetool/$WDT_PKG -d /u01/wdt         && cd /u01/wdt/weblogic-deploy/bin         && ./createDomain.sh         -oracle_home /u01/oracle         -domain_home /u01/oracle/Middleware/domains/asr_domain/         -domain_type WLS         -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip' returned a non-zero code: 98

**Comment by ddsharpe** [comment]
@MaheshwarReddyGade I cannot reproduce this on the current release.  What version of WDT are you using?  Can you retry with WDT 1.6.2 or newer?

**Comment by jshum2479** [comment]
Looking at the Dockerfile,  there are couple of lines  (these come from your additional build commands)

        RUN  mkdir -p /u01/oracle/Middleware/domains/asr_domain/
            COPY --chown=oracle:oinstall config.xml /u01/oracle/Middleware/domains/asr_domain/

It comes before  
FROM WLS_BUILD as WDT_BUILD

You shouldn't need to do that (The COPY will fail since it's trying to look for config.xml).   Can you remove the additionalBuildCommands option and also remove the extra / in the wdtDomainHome parameter value ?

**Comment by MaheshwarReddyGade** [comment]
> @MaheshwarReddyGade I cannot reproduce this on the current release. What version of WDT are you using? Can you retry with WDT 1.6.2 or newer?

@ddsharpe  Thanks for helping .. My WDT version is weblogic-deploy-tooling-1.6.2

**Comment by MaheshwarReddyGade** [comment]
> Looking at the Dockerfile, there are couple of lines (these come from your additional build commands)
> 
> ```
>     RUN  mkdir -p /u01/oracle/Middleware/domains/asr_domain/
>         COPY --chown=oracle:oinstall config.xml /u01/oracle/Middleware/domains/asr_domain/
> ```
> 
> It comes before
> FROM WLS_BUILD as WDT_BUILD
> 
> You shouldn't need to do that (The COPY will fail since it's trying to look for config.xml). Can you remove the additionalBuildCommands option and also remove the extra / in the wdtDomainHome parameter value ?

@jshum2479 Thanks for helping .. I removed this line later 
 COPY --chown=oracle:oinstall config.xml /u01/oracle/Middleware/domains/asr_domain/

As i'm getting config.xml file not found error i added this. However i removed it later .. 
with or without additionalBuild Command , It is failing with domain does not exist .. After adding mkdir -p <domain home> in additional args , It is failing with <domainhome>/config.xml file does not exist ..

**Comment by ddsharpe** [comment]
@MaheshwarReddyGade I was able to recreate your error message by using a very old version, 0.13, of WDT.

Because I do not see the version number in the stdout of the post that you provided, this makes me believe that you have an older version of WDT than you think.  Since about May 2019, the version number of WDT is logged at INFO for all of the WDT scripts.  And, the broken directory that had this same signature check was fixed over a year ago (circa Oct, 2018).
You should have seen a version line that looks like:
####<Jan 15, 2020 4:36:24 PM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.6.2:master.ca8476a:Dec 16, 2019 23:54 UTC>

Please try manually downloading a new version of WDT from the Github releases tab, and manually add that zip to the image tool cache (after deleting the previous entry) using "imagetool cache addInstaller --type wdt ..."

**Comment by MaheshwarReddyGade** [comment]
> @MaheshwarReddyGade I was able to recreate your error message by using a very old version, 0.13, of WDT.
> 
> Because I do not see the version number in the stdout of the post that you provided, this makes me believe that you have an older version of WDT than you think. Since about May 2019, the version number of WDT is logged at INFO for all of the WDT scripts. And, the broken directory that had this same signature check was fixed over a year ago (circa Oct, 2018).
> You should have seen a version line that looks like:
> ####<Jan 15, 2020 4:36:24 PM> <The WebLogic Deploy Tooling createDomain version is 1.6.2:master.ca8476a:Dec 16, 2019 23:54 UTC>
> 
> Please try manually downloading a new version of WDT from the Github releases tab, and manually add that zip to the image tool cache (after deleting the previous entry) using "imagetool cache addInstaller --type wdt ..."

@ddsharpe Thanks for your help. Its good to know that you have re produced my issues .. thanks a ton.
I tried using latest version too, still i'm getting same error. Are able to create domain with latest version?

[oracle@ebsasserter bin]$ imagetool cache listItems
Cache contents
cache.dir=/home/oracle/cache
wdt_1.4.0_url=https://github.com/oracle/weblogic-deploy-tooling/releases/download/weblogic-deploy-tooling-1.4.0/weblogic-deploy.zip
30675853_12.2.1.3.0=/home/oracle/cache/p30675853_122130_Generic.zip
wdt_latest_url=https://github.com/oracle/weblogic-deploy-tooling/releases/download/weblogic-deploy-tooling-1.6.2/weblogic-deploy.zip
wdt_0.22=/u01/install/software/weblogic-deploy.zip
wdt_1.6.2=/u01/install/software/weblogic-deploy.zip
jdk_8u211=/u01/install/software/jdk-8u211-linux-x64.tar.gz
wls_12.2.1.3.0=/u01/install/software/fmw_12.2.1.3.0_wls_Disk1_1of1.zip
30386660_12.2.1.3.0=/home/oracle/cache/p30386660_122130_Generic.zip
28186730_opatch=/home/oracle/cache/p28186730_139400_Generic.zip
wdt_1.6.2_url=https://github.com/oracle/weblogic-deploy-tooling/releases/download/weblogic-deploy-tooling-1.6.2/weblogic-deploy.zip
[oracle@ebsasserter bin]$ 

COMMAND i'm using to run:
cd /u01/install/projects/tools/imagetool/bin
. ./setup.sh
export JAVA_HOME=/u01/install/software/jdk1.8.0_211
export PATH=$JAVA_HOME/bin:$PATH
imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u211 --wdtModel=/u01/install/software/sample.yaml --wdtVariables=/u01/oracle/properties/domain.properties --wdtArchive /u01/install/software/archive.zip --wdtDomainHome /u01/oracle/Middleware/domains/asr_domain --wdtVersion 1.6.2 --chown oracle:oinstall --user maheswar.xxxx@xxxx.com --password ********

**Comment by ddsharpe** [comment]
@MaheshwarReddyGade Creating the domain with the 1.6.2 version works for me.  Looking at your cache, I think I see your cause:
wdt_0.22=/u01/install/software/weblogic-deploy.zip
wdt_1.6.2=/u01/install/software/weblogic-deploy.zip

I recommend that you remove all the wdt versions from your cache, and download the 1.6.2 version and add it.  I suspect that you are using version 0.22 by mistake.

**Comment by MaheshwarReddyGade** [comment]
> @MaheshwarReddyGade Creating the domain with the 1.6.2 version works for me. Looking at your cache, I think I see your cause:
> wdt_0.22=/u01/install/software/weblogic-deploy.zip
> wdt_1.6.2=/u01/install/software/weblogic-deploy.zip
> 
> I recommend that you remove all the wdt versions from your cache, and download the 1.6.2 version and add it. I suspect that you are using version 0.22 by mistake.

@ddsharpe After i removing cache items in imagetool & adding again. It worked :)
Thank you for your help.
I would request you to help for one more issue .. 

Here is the ERROR :
=======================================================================================================
####<Jan 16, 2020 5:18:53 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.6.2:master.ca8476a:Dec 16, 2019 23:54 UTC>
####<Jan 16, 2020 5:18:53 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05002> <Performing validation in TOOL mode for WebLogic Server version 12.2.1.3.0 and WLST OFFLINE mode>
####<Jan 16, 2020 5:18:53 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05003> <Performing model validation on the /u01/wdt/models/sample.yaml model file>
####<Jan 16, 2020 5:18:53 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05005> <Performing archive validation on the /u01/wdt/models/archive.zip archive file>
####<Jan 16, 2020 5:18:53 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the domainInfo section of the model file>
####<Jan 16, 2020 5:18:53 AM> <SEVERE> <Validator> <__validate_single_path_in_archive> <WLSDPLY-05024> <Attribute domainLibraries in model location domainInfo:/ references entry wlsdeploy/domainLibraries/fndext.jar that is not found in the archive file /u01/wdt/models/archive.zip>
####<Jan 16, 2020 5:18:53 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the topology section of the model file>
####<Jan 16, 2020 5:18:54 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the resources section of the model file>
####<Jan 16, 2020 5:18:54 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the appDeployments section of the model file>
####<Jan 16, 2020 5:18:54 AM> <SEVERE> <Validator> <__validate_single_path_in_archive> <WLSDPLY-05024> <Attribute SourcePath in model location appDeployments:/Application/ebsasserter_ebsdb references entry wlsdeploy/applications/ebsasserter_ebsdb that is not found in the archive file /u01/wdt/models/archive.zip>
####<Jan 16, 2020 5:18:54 AM> <SEVERE> <create> <validate_model> <WLSDPLY-20001> <createDomain did not create the domain because validation failed>

Issue Log for createDomain version 1.6.2 running WebLogic version 12.2.1.3.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-05024: Attribute domainLibraries in model location domainInfo:/ references entry wlsdeploy/domainLibraries/fndext.jar that is not found in the archive file /u01/wdt/models/archive.zip
        2. WLSDPLY-05024: Attribute SourcePath in model location appDeployments:/Application/ebsasserter_ebsdb references entry wlsdeploy/applications/ebsasserter_ebsdb that is not found in the archive file /u01/wdt/models/archive.zip
        3. WLSDPLY-20001: createDomain did not create the domain because validation failed

Total:       WARNING :     0    SEVERE :     3

createDomain.sh failed (exit code = 2)
Removing intermediate container 1c9bacac01f4
[SEVERE ] Response code: -1, message: docker command failed with error: The command '/bin/sh -c unzip -q /tmp/imagetool/$WDT_PKG -d /u01/wdt         && cd /u01/wdt/weblogic-deploy/bin         && ./createDomain.sh         -oracle_home /u01/oracle         -domain_home /u01/oracle/Middleware/domains/asr_domain         -domain_type WLS         -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip' returned a non-zero code: 2
=======================================================================================================

I unzipped archive.zip in temp dir to see these files exist .. These files exists.

[oracle@ebsasserter archive]$ ls -ld wlsdeploy/applications/ebsasserter_ebsdb
drwxr-xr-x. 4 oracle oinstall 4096 Dec 28 11:11 wlsdeploy/applications/ebsasserter_ebsdb
[oracle@ebsasserter archive]$ ls -ltr  wlsdeploy/domainLibraries/fndext.jar
-rw-r--r--. 1 oracle oinstall 273813 Dec 27 06:46 wlsdeploy/domainLibraries/fndext.jar
[oracle@ebsasserter archive]$ ls -ltr wlsdeploy/applications/ebsasserter_ebsdb/*.jar
-rw-r--r--. 1 oracle oinstall 5616737 Dec 27 06:47 wlsdeploy/applications/ebsasserter_ebsdb/idcs-wallet-19.3.3-1.6.0.jar
[oracle@ebsasserter archive]$

my yaml file syntax is below( not copying entire yaml)

domainInfo:
    AdminUserName: '@@PROP:ADMIN_USER@@'
    AdminPassword: '@@PROP:ADMIN_PWD@@'
    domainLibraries: wlsdeploy/domainLibraries/fndext.jar

appDeployments:
    Application:
        ebsasserter_ebsdb:
            SourcePath: 'wlsdeploy/applications/ebsasserter_ebsdb'
            ModuleType: jar
            StagingMode: nostage
            Target: AsrPOC_Cluster


is my syntax correct ? Am i missing anything here ? Kindly help.

**Comment by MaheshwarReddyGade** [comment]
@ddsharpe After i removing cache items in imagetool & adding again. It worked :)
Thank you for your help.  One more issue came now .. working on it ..

**Comment by MaheshwarReddyGade** [comment]
@ddsharpe @jshum2479 
I'm getting new ERROR now . Need your kind help please...
####<Jan 16, 2020 4:57:45 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Unable to copy domain library /u01/wdt/weblogic-deploy/bin/w to directory /u01/oracle/Middleware/domains/asr_domain/lib>



ERROR:
####<Jan 16, 2020 4:57:41 PM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12206> <Closing templates for domain asr_domain>
####<Jan 16, 2020 4:57:45 PM> <INFO> <LibraryHelper> <install_domain_libraries> <WLSDPLY-12235> <Installing domain library w to lib directory of /u01/oracle/Middleware/domains/asr_domain>
####<Jan 16, 2020 4:57:45 PM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Unable to copy domain library /u01/wdt/weblogic-deploy/bin/w to directory /u01/oracle/Middleware/domains/asr_domain/lib>

Issue Log for createDomain version 1.6.2 running WebLogic version 12.2.1.3.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Unable to copy domain library /u01/wdt/weblogic-deploy/bin/w to directory /u01/oracle/Middleware/domains/asr_domain/lib

Total:       WARNING :     0    SEVERE :     1
createDomain.sh failed (exit code = 2)

Removing intermediate container b2242ef0ffd2
[SEVERE ] Response code: -1, message: docker command failed with error: The command '/bin/sh -c unzip -q /tmp/imagetool/$WDT_PKG -d /u01/wdt         && cd /u01/wdt/weblogic-deploy/bin         && ./createDomain.sh         -oracle_home /u01/oracle         -domain_home /u01/oracle/Middleware/domains/asr_domain         -domain_type WLS         -variable_file /u01/wdt/models/domain.properties -model_file /u01/wdt/models/sample.yaml -archive_file /u01/wdt/models/archive.zip' returned a non-zero code: 2



Please guide me if  i'm missing  anything here ?

**Comment by ddsharpe** [comment]
@MaheshwarReddyGade The error message does not match the artifacts that you posted above.  I suspect that you have changed something by mistake or during your trials of trying to get things to work.

First, you need to fix your archive ZIP.  The first folder in your archive is "archive".  It should be "wlsdeploy".  You have an extra layer in your archive and that top layer should be removed.

Second, please check your model and verify the domainLibraries attribute:
domainInfo:
    AdminUserName: '@@PROP:ADMIN_USER@@'
    AdminPassword: '@@PROP:ADMIN_PWD@@'
    domainLibraries: [ wlsdeploy/domainLibraries/fndext.jar ]

**Comment by MaheshwarReddyGade** [comment]
> @MaheshwarReddyGade The error message does not match the artifacts that you posted above. I suspect that you have changed something by mistake or during your trials of trying to get things to work.
> 
> First, you need to fix your archive ZIP. The first folder in your archive is "archive". It should be "wlsdeploy". You have an extra layer in your archive and that top layer should be removed.
> 
> Second, please check your model and verify the domainLibraries attribute:
> domainInfo:
> AdminUserName: '@@prop:ADMIN_USER@@'
> AdminPassword: '@@prop:ADMIN_PWD@@'
> domainLibraries: [ wlsdeploy/domainLibraries/fndext.jar ]

@ddsharpe You are right .. my archive.zip was not correctly zipped . I fixed archive.zip already ..
I have domainLibraries: [ wlsdeploy/domainLibraries/fndext.jar ] this defined in sample.yaml file 

But Error says - Unable to copy domain library /u01/wdt/weblogic-deploy/bin/w to directory /u01/oracle/Middleware/domains/asr_domain/lib>

I have no clue why i'm getting this error .. 

below is the jar file when i unzipped archive.zip
[oracle@ebsasserter software]$ ls -ltr wlsdeploy/domainLibraries/fndext.jar
-rwxrwxrwx. 1 oracle oinstall 273813 Dec 27 06:46 wlsdeploy/domainLibraries/fndext.jar
[oracle@ebsasserter software]$

**Comment by MaheshwarReddyGade** [comment]
> @MaheshwarReddyGade The error message does not match the artifacts that you posted above. I suspect that you have changed something by mistake or during your trials of trying to get things to work.
> 
> First, you need to fix your archive ZIP. The first folder in your archive is "archive". It should be "wlsdeploy". You have an extra layer in your archive and that top layer should be removed.
> 
> Second, please check your model and verify the domainLibraries attribute:
> domainInfo:
> AdminUserName: '@@prop:ADMIN_USER@@'
> AdminPassword: '@@prop:ADMIN_PWD@@'
> domainLibraries: [ wlsdeploy/domainLibraries/fndext.jar ]

@ddsharpe Now my domain got created successfully ..
Thank you very much for your help ..

**Comment by ddsharpe** [comment]
Great!  Glad its working for you.
