### ISSUE TITLE
ADMIN Server not starting 

### ISSUE THREAD

**Issue by MaheshwarReddyGade** [oracle/weblogic-image-tool#125]
I created WLS domain image using imagetool 

Here is the completed log:

COMPLETED LOG:
####<Jan 17, 2020 5:59:11 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.6.2:master.ca8476a:Dec 16, 2019 23:54 UTC>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05002> <Performing validation in TOOL mode for WebLogic Server version 12.2.1.3.0 and WLST OFFLINE mode>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05003> <Performing model validation on the /u01/wdt/models/sample.yaml model file>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_file> <WLSDPLY-05005> <Performing archive validation on the /u01/wdt/models/archive.zip archive file>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the domainInfo section of the model file>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the topology section of the model file>
####<Jan 17, 2020 5:59:12 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the resources section of the model file>
####<Jan 17, 2020 5:59:13 AM> <INFO> <Validator> <__validate_model_section> <WLSDPLY-05008> <Validating the appDeployments section of the model file>
####<Jan 17, 2020 5:59:13 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /u01/wdt/weblogic-deploy/lib/model_filters.json>
####<Jan 17, 2020 5:59:13 AM> <INFO> <DomainCreator> <__create_domain> <WLSDPLY-12203> <Creating domain of type WLS>
####<Jan 17, 2020 5:59:13 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12210> <Selecting base template named Basic WebLogic Server Domain>
####<Jan 17, 2020 5:59:14 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12212> <Loading selected templates>
####<Jan 17, 2020 5:59:17 AM> <INFO> <DomainCreator> <__set_domain_name> <WLSDPLY-12227> <Changing domain name from base_domain to asr_domain>
####<Jan 17, 2020 5:59:17 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating UnixMachine with the name ebsasserter>
####<Jan 17, 2020 5:59:18 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for JDBCSystemResource ebsdbDS>
####<Jan 17, 2020 5:59:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name AsrPOC_Cluster>
####<Jan 17, 2020 5:59:18 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server asrPOCserver1>
####<Jan 17, 2020 5:59:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name AdminServer>
####<Jan 17, 2020 5:59:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name asrPOCserver1>
####<Jan 17, 2020 5:59:19 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating MigratableTarget with the name asrPOCserver1 (migratable)>
####<Jan 17, 2020 5:59:19 AM> <INFO> <Creator> <_create_mbean> <WLSDPLY-20013> <Updating NMProperties>
####<Jan 17, 2020 5:59:19 AM> <INFO> <DomainCreator> <__create_domain_with_select_template> <WLSDPLY-12206> <Closing templates for domain asr_domain>
####<Jan 17, 2020 5:59:23 AM> <INFO> <LibraryHelper> <install_domain_libraries> <WLSDPLY-12215> <Installing domain library wlsdeploy/domainLibraries/fndext.jar from archive to lib directory of /u01/oracle/Middleware/domains/asr_domain>
####<Jan 17, 2020 5:59:23 AM> <INFO> <LibraryHelper> <extract_classpath_libraries> <WLSDPLY-12218> <The archive file /u01/wdt/models/archive.zip contains no classpath libraries to install>
####<Jan 17, 2020 5:59:23 AM> <INFO> <LibraryHelper> <install_domain_scripts> <WLSDPLY-12241> <The model did not specify any domain scripts to install>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09608> <Updating JDBCSystemResource ebsdbDS>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09604> <Updating JdbcResource for JDBCSystemResource ebsdbDS>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09601> <Adding JDBCConnectionPoolParams to JdbcResource>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09601> <Adding JDBCDataSourceParams to JdbcResource>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_model_elements> <WLSDPLY-09601> <Adding JDBCDriverParams to JdbcResource>
####<Jan 17, 2020 5:59:23 AM> <INFO> <DatasourceDeployer> <_add_named_elements> <WLSDPLY-09606> <Adding Properties user to JDBCDriverParams>
####<Jan 17, 2020 5:59:23 AM> <INFO> <ApplicationDeployer> <__add_applications> <WLSDPLY-09301> <Adding Application ebsasserter_ebsdb to Domain asr_domain>

Issue Log for createDomain version 1.6.2 running WebLogic version 12.2.1.3.0 offline mode:

Total:       WARNING :     0    SEVERE :     0

createDomain.sh completed successfully (exit code = 0)
Removing intermediate container 97d3a7e97826
 ---> 3c7fa33e41ef
Step 38/50 : FROM OS_UPDATE as FINAL_BUILD
 ---> 9bf864ae8de8
Step 39/50 : ARG ADMIN_NAME
 ---> Running in fb1a73be2250
Removing intermediate container fb1a73be2250
 ---> 18bc725abcb8
Step 40/50 : ARG ADMIN_HOST
 ---> Running in ece9db837918
Removing intermediate container ece9db837918
 ---> 4e1d2aeadabd
Step 41/50 : ARG ADMIN_PORT
 ---> Running in 4e5320d75523
Removing intermediate container 4e5320d75523
 ---> 7cafc531a44d
Step 42/50 : ARG MANAGED_SERVER_PORT
 ---> Running in 5b13eaea3560
Removing intermediate container 5b13eaea3560
 ---> 033c68b95253
Step 43/50 : ENV ORACLE_HOME=/u01/oracle     JAVA_HOME=/u01/jdk     ADMIN_NAME=${ADMIN_NAME:-admin-server}     ADMIN_HOST=${ADMIN_HOST:-wlsadmin}     ADMIN_PORT=${ADMIN_PORT:-7001}     MANAGED_SERVER_NAME=${MANAGED_SERVER_NAME:-}     MANAGED_SERVER_PORT=${MANAGED_SERVER_PORT:-8001}     DOMAIN_HOME=/u01/oracle/Middleware/domains/asr_domain     LC_ALL=${DEFAULT_LOCALE:-en_US.UTF-8}     PROPERTIES_FILE_DIR=/u01/oracle/properties     PATH=${PATH}:/u01/jdk/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle:$/u01/oracle/Middleware/domains/asr_domain/bin
 ---> Running in 8fe80d380df0
Removing intermediate container 8fe80d380df0
 ---> 622db12798ba
Step 44/50 : LABEL com.oracle.weblogic.imagetool.buildid="206ea75b-5def-4710-a0c4-38f2c19931d1"
 ---> Running in 987ed8db54a2
Removing intermediate container 987ed8db54a2
 ---> 65c404f3e047
Step 45/50 : COPY --from=JDK_BUILD --chown=oracle:oinstall /u01/jdk /u01/jdk/
 ---> 8b3b46a623a7
Step 46/50 : COPY --from=WLS_BUILD --chown=oracle:oinstall /u01/oracle /u01/oracle/
 ---> 5d2baca72e9a
Step 47/50 : COPY --from=WDT_BUILD --chown=oracle:oinstall /u01/oracle/Middleware/domains/asr_domain /u01/oracle/Middleware/domains/asr_domain/
 ---> 2a9093e367fb
Step 48/50 : EXPOSE $ADMIN_PORT $MANAGED_SERVER_PORT
 ---> Running in 9d083a346bf2
Removing intermediate container 9d083a346bf2
 ---> d4120c0adae7
Step 49/50 : USER oracle
 ---> Running in fbbeb75aaa49
Removing intermediate container fbbeb75aaa49
 ---> 3461a2892fe3
Step 50/50 : WORKDIR /u01/oracle/Middleware/domains/asr_domain
 ---> Running in a97811fa2dac
Removing intermediate container a97811fa2dac
 ---> d52f69db54b7
Successfully built d52f69db54b7
Successfully tagged wls:12.2.1.3.0
[oracle@ebsasserter bin]$
[oracle@ebsasserter bin]$
[oracle@ebsasserter bin]$
[oracle@ebsasserter bin]$
[oracle@ebsasserter bin]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
wls                 12.2.1.3.0          d52f69db54b7        2 minutes ago       1.57GB
oraclelinux         7-slim              0d49b70bc432        4 weeks ago         118MB
[oracle@ebsasserter bin]$

 docker run -d --name ebsasserter --hostname ebsasserter  -v /u01/oracle/properties/domain.properties:/u01/oracle/properties -p 7001:7001  wls:12.2.1.3.0

when i run above command , Nothing happens , it is immediately getting exited .. 
how to debug ?

**Comment by ddsharpe** [comment]
Your docker command did not specify a start script.  The Image Tool does not insert a start script by default.  You need to specify what you want Docker to run, like "docker run ... /u01/domains/asr_domain/startWebLogic.sh".  Or, you need to add the "CMD" command to the Dockerfile during the build using the --additionalBuildCommands option in Image Tool.

**Comment by MaheshwarReddyGade** [comment]
> Your docker command did not specify a start script. The Image Tool does not insert a start script by default. You need to specify what you want Docker to run, like "docker run ... /u01/domains/asr_domain/startWebLogic.sh". Or, you need to add the "CMD" command to the Dockerfile during the build using the --additionalBuildCommands option in Image Tool.

@ddsharpe oops i see there is NO CMD and ENTRYPOINT when it generates ....

Can you please give me some examples how we can do this using additonalbuild argument in imagetool?

**Comment by ddsharpe** [comment]
See documentation at https://github.com/oracle/weblogic-image-tool/blob/master/site/create-image.md#additional-information

In this case, you will want to add the CMD with something like 
[final-build-commands]
CMD ["/u01/domains/asr_domain/startWebLogic.sh"]

**Comment by MaheshwarReddyGade** [comment]
@ddsharpe thanks i'm able to start admin server now ..
