### ISSUE TITLE
Server is running in Development Mode and the System Console to read the password securely from the command line was not found.

### ISSUE THREAD

**Issue by MaheshwarReddyGade** [oracle/weblogic-image-tool#127]
While starting MS getting below error :

Starting WLS with line:
/u01/jdk/bin/java -server   -Xms256m -Xmx512m -XX:CompileThreshold=8000 -cp /u01/oracle/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=ms-1 -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy  -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader  -javaagent:/u01/oracle/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/u01/oracle/wlserver/server -Dweblogic.home=/u01/oracle/wlserver/server   -Dweblogic.management.server=http://ebsasserter.subnet.vcn.oraclevcn.com:7001   weblogic.Server
<Jan 26, 2020 12:36:52 PM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
<Jan 26, 2020 12:36:52 PM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
<Jan 26, 2020 12:36:52 PM GMT> <Notice> <WebLogicServer> <BEA-000395> <The following extensions directory contents added to the end of the classpath:
/u01/oracle/Middleware/domains/asr_domain/lib/fndext.jar.>
<Jan 26, 2020 12:36:54 PM GMT> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.211-b12 from Oracle Corporation.>
<Jan 26, 2020 12:36:54 PM GMT> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>
<Jan 26, 2020 12:36:54 PM GMT> <Info> <Security> <BEA-090065> <Getting boot identity from user.>
Enter username to boot WebLogic server:<Jan 26, 2020 12:36:54 PM GMT> <Error> <Security> <BEA-090783> 
<Server is running in Development Mode and the System Console to read the password securely from the command line was not found.
 The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.>
<Jan 26, 2020 12:36:54 PM GMT> <Notice> <WebLogicServer> <BEA-000388> <JVM called the WebLogic Server shutdown hook. The server will force shutdown now.>
<Jan 26, 2020 12:36:54 PM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.>
[oracle@ebsasserter bin]$

**command i used to create domain:**
cd /u01/install/projects/tools/imagetool/bin
. ./setup.sh
export JAVA_HOME=/u01/install/software/jdk1.8.0_211
export PATH=$JAVA_HOME/bin:$PATH
imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --jdkVersion=8u211 --wdtModel=/u01/install/software/sample.yaml --wdtVariables=/u01/oracle/properties/domain.properties --wdtArchive /u01/install/software/archive.zip --wdtDomainHome /u01/oracle/Middleware/domains/asr_domain --wdtVersion 1.6.2 --chown oracle:oinstall --additionalBuildCommands=/u01/install/projects/tools/imagetool/bin/buildargs --user maheswar@******.com --password *********

**Start MS:**
docker run -d --name ms-1 --link ebsasserter:ebsasserter --network=SampleNET -p 8001:8001 -v /u01/oracle/properties/domain.properties:/u01/oracle/properties -e MS_NAME=ms-1 wls:12.2.1.3.0 /u01/oracle/Middleware/domains/asr_domain/bin/startManagedWebLogic.sh ms-1 http://ebsasserter.subnet.vcn.oraclevcn.com:7001

**start ADMIN Server:**
docker run -d --name ebsasserter --hostname ebsasserter --network=SampleNET -v /u01/oracle/properties/domain.properties:/u01/oracle/properties -p 7001:7001  wls:12.2.1.3.0

**Comment by ddsharpe** [comment]
Please attach your WDT model and properties file.  If your model or properties file contains passwords, please change the values to XXXX before attaching them.

**Comment by MaheshwarReddyGade** [comment]
cat /u01/install/software/sample.yaml
domainInfo:
    AdminUserName: '@@PROP:ADMIN_USER@@'
    AdminPassword: '@@PROP:ADMIN_PWD@@'
topology:
    Name: asr_domain
    ProductionModeEnabled: false
    NMProperties:
        ListenPort: 5558
        JavaHome: /u01/install/software/jdk1.8.0_211
        LogFile: /u01/oracle/Middleware/domains/asr_domain/nodemanager/nodemanager.log
        ListenAddress: ebsasserter.public.vcn.oraclevcn.com
        DomainsFile: /u01/oracle/Middleware/domains/asr_domain/nodemanager/nodemanager.domains
        NodeManagerHome: /u01/oracle/Middleware/domains/asr_domain/nodemanager
        PropertiesVersion: 12.2.1.3.0
        weblogic.StartScriptName: startWebLogic.sh
    Cluster:
        AsrPOC_Cluster:
            DefaultLoadAlgorithm: 'round-robin'
            WeblogicPluginEnabled: true
    Server:
        AdminServer:
            Machine: ebsasserter
            KeyStores: CustomIdentityAndJavaStandardTrust
            ListenAddress: ebsasserter.public.vcn.oraclevcn.com
            SSL:
                HostnameVerificationIgnored: true
                OutboundCertificateValidation: BuiltinSSLValidationOnly
                InboundCertificateValidation: BuiltinSSLValidationOnly
        asrPOCserver1:
            ListenPort: 7002
            Machine: ebsasserter
            KeyStores: CustomIdentityAndJavaStandardTrust
            Cluster: AsrPOC_Cluster
            ListenAddress: ebsasserter.public.vcn.oraclevcn.com
            JTAMigratableTarget:
                Cluster: AsrPOC_Cluster
                UserPreferredServer: asrPOCserver1
    MigratableTarget:
        asrPOCserver1 (migratable):
            Cluster: AsrPOC_Cluster
            MigrationPolicy: manual
            UserPreferredServer: asrPOCserver1
            Notes: This is a system generated default migratable target for a server. Do not delete manually.
    UnixMachine:
        ebsasserter:
            NodeManager:
                NMType: Plain
                ListenAddress: ebsasserter.public.vcn.oraclevcn.com
                ListenPort: 5558
resources:
    JDBCSystemResource:
        ebsdbDS:
            Target: AsrPOC_Cluster
            DescriptorFileName: 'jdbc/ebsdbDS-6357-jdbc.xml'
            JdbcResource:
                DatasourceType: GENERIC
                JDBCConnectionPoolParams:
                    TestTableName: SQL ISVALID
                JDBCDataSourceParams:
                    JNDIName: ebsdbDS
                JDBCDriverParams:
                    URL: 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=YES)(FAILOVER=YES)(ADDRESS=(PROTOCOL=tcp)(HOST=apps.example.com)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ebsdb)))'
                    PasswordEncrypted: '@@PROP:EBSDB_PWD@@'
                    DriverName: oracle.jdbc.OracleDriver
                    Properties:
                        user:
                            Value: apps
appDeployments:
    Application:
        ebsasserter_ebsdb:
            SourcePath: 'wlsdeploy/applications/ebsasserter_ebsdb/ebs.war'
            ModuleType: war
            StagingMode: nostage
            Target: AsrPOC_Cluster


properties file:
[oracle@ebsasserter software]$ cat /u01/oracle/properties/domain.properties
ADMIN_USER=weblogic
ADMIN_PWD=******
username=weblogic
password=*****
EBSDB_PWD=****
NM_USER=weblogic
NM_PWD=***

**Comment by ddsharpe** [comment]
@MaheshwarReddyGade This message in your post:
<Server is running in Development Mode and the System Console to read the password securely from the command line was not found.
The System Console is not present if stdin, stdout, or stderr is redirected when starting WebLogic Server.>
indicates that the boot.properties file is missing from the managed server folder.  I tried to reproduce this use case with the current release, but could not.  I built the domain using WDT and Image Tool and verified that the boot.properties is created for each of the managed servers (when NOT in production mode).  

Please look in the domain home directory under $DOMAIN_HOME/servers and verify that the image has a boot.properties for each of your servers in the security folder.

**Comment by ddsharpe** [comment]
Closed due to no response.  @MaheshwarReddyGade Please re-open if there is additional feedback.
