### ISSUE TITLE
typo in quickstart.md

### ISSUE THREAD

**Issue by xiancao** [oracle/weblogic-image-tool#17]
1) in the second command to "Use the Cache Tool to add the installers:" 
imagetool cache addInstaller --type wls --version 12.2.1.3.0 --path /home/acmeuser/wls-installers/fmw_12.2.1.3.0_wls_Disk1_1of1.zip
**.tar.gz**
'.tar.gz' needs to be deleted

2) in the section "Creating an image with no Internet access", in the command:
imagetool cache addPatch --patchId p27342434 --version 12.2.1.3.0 --path /home/acmeuser/cache/**p27342434_122130_Generic .zip** **-user** username@mycompany.com --passwordEnv MYPWD

There should be no space in "p27342434_122130_Generic .zip"
"-user" should be "--user"

3) in the section "Patching an existing image", in the command:
imagetool update --fromImage wls:12.2.1.3.0 --tag wls:12.2.1.3.4 --patches 27342434 **--version 12.2.1.3.0** --useCache always
There is no options for '--version' in 'imagetool update' command. We need to remove that.

**Comment by jshum2479** [comment]
Thanks Xian.  It's done
