### ISSUE TITLE
Support Podman as alternative to Docker

### ISSUE THREAD

**Issue by brophyja** [oracle/weblogic-image-tool#186]
Please add support for Podman, which is a replacement for the Docker container runtime.

Red Hat is moving from Docker to Podman as the preferred container runtime:
https://access.redhat.com/solutions/3696691

Oracle Enterprise Linux 8 supports Podman:
https://docs.oracle.com/en/operating-systems/oracle-linux/8/relnotes8.0/ol8-features-changes.html#ol8-features-container

**Comment by ddsharpe** [comment]
The move to Podman is a planned enhancement for the 2.0 release.

**Comment by golem0** [comment]
Using `alternatives` to create a symbolic link from /usr/bin/docker to /usr/bin/podman worked for me.

**Comment by ddsharpe** [comment]
Release 1.9.11 includes an option that supports Podman (Experimental at first). @brophyja @golem0

**Comment by ddsharpe** [comment]
@brophyja @golem0 Have you had a chance to try Image Tool with Podman?  Any feedback?
