### ISSUE TITLE
Support configurable model home location for WDT images

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-image-tool#190]
(1) WDT image generation hard codes the model directory to `/u01/wdt/models`.  Let's make this configurable.  

The equivalent field in a WKO domain resource is `spec.configuration.model.modelHome`, plus the WKO runtime sets the `WDT_MODEL_HOME` environment variable internally.

(2) WDT image generation should still install WDT binaries for 'model only' mode even when no model files are supplied.

**Comment by ddsharpe** [comment]
This is two changes:
- Add `--wdtModelHome /some/directory` to the command line in WDT options.
- Fix "if" statement to check for "modelsOnly" so that the WDT installer and archive are included (with or without a model)

**Comment by jshum2479** [comment]
How about wdt binary ?  I assume this only affect the models etc... but the binary still goes to 
`/u01/wdt/weblogic-deploy`
