### ISSUE TITLE
Rebase resulting image can not be used for Update (rebase doesn't set DOMAIN_HOME)

### ISSUE THREAD

**Issue by Omar007** [oracle/weblogic-image-tool#193]
When using `imagetool rebase` to create an updated image, the resulting image can not be used as input to `imagetool update` at a later point in time to perform updates to the domain.  

Rebase does not set the DOMAIN_HOME variable and as a result, update will error out with the following message:
> Response code: -1, message: WDT Operation is set to UPDATE, but the DOMAIN_HOME environment variable was not defined in the base image

**Comment by ddsharpe** [comment]
@Omar007 thank you, we will fix this in the next release.
