### ISSUE TITLE
Main Release Download URL is corrupted in main project README

### ISSUE THREAD

**Issue by domenicovenuto** [oracle/weblogic-image-tool#207]
The Releases download URL in the project main project README page is corrupted

https://github.com/oracle/weblogic-image-tool/blob/master/README.md

This is the corrupted link (it returns a 404 HTTP error code)

https://github.com/oracle/weblogic-image-tool/blob/master/releases

Please check the README or FIX the release page

**Comment by ddsharpe** [comment]
Thank you.  Done
