### ISSUE TITLE
Customizable response file for middleware install

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-image-tool#21]
All the user to provide a custom response file for the middleware install step.  Currently, the middleware response file is fixed and internal.  Since the installer can be customized and its responses could vary, allow the user to override the default response file.

**Comment by ddsharpe** [comment]
@lukasged Were you the one that requested this feature at the CAB in Rome?

**Comment by lukasged** [comment]
@ddsharpe it were my colleagues @antonionappi88 and Artur that requested for it. We work on the same project.

**Comment by ddsharpe** [comment]
@antonionappi88 What is the use case for this request?  I created the ability to add the response file, but I stopped short of merging it.  The response file allows the installation directory to change which would affect the Oracle Home ENV variable.  Since these need to be in sync between the response file and the Dockerfile, I stopped because this could cause the user confusion and trouble unless I try to scan the file and handle that case.  What are the values that are interesting for you in the response file?

**Comment by lukasged** [comment]
@ddsharpe we provide the response file basically to set two values:
- `INSTALL_TYPE` (`WebLogic Server` or `Complete with Examples`)
- `ORACLE_HOME`

We will check if we really need to change the _ORACLE_HOME_ value or if we could just rely on the one set by the tool.

**Comment by antonionappi88** [comment]
@ddsharpe We are used to have our own rpms to install WebLogic binaries. Our infrastructure on Kubernetes is using that, and we install everything in custom directories.

To integrate this tool with our kubernetes deployment in a smoothly way and the best would be to keep the same `ORACLE_HOME`.
