### ISSUE TITLE
image tool is looking for wrong jdk setp

### ISSUE THREAD

**Issue by eugsim1** [oracle/weblogic-image-tool#211]
imagetool:1.9.4

imagetool create --tag wls:12.2.1.4.0 \
--latestPSU --version 12.2.1.4.0 \
--user  XXXX@oracle.com \
--passwordFile passwd.txt

[INFO   ] Image Tool build ID: 780e6128-c69b-4903-84cc-fc5a4ea08b3e
[INFO   ] Temporary directory used for docker build context: /home/oracle/wlsimgbuilder_temp5602806564526456300
[SEVERE ] Response code: -1, message: Installer with key="jdk_8u202" is not in the local cache, please download the installer and add it to the cache with "imagetool cache addInstaller ..."

why i need this installer i have put in the cache :
 imagetool cache listItems
Cache contents
cache.dir=/home/oracle/cache
wls_12.2.1.4.0=/home/oracle/stage/installers/fmw_12.2.1.4.0_wls_Disk1_1of1.zip
jdk_8u261=/home/oracle/stage/installers/jdk-8u261-linux-x64.tar.gz

**Comment by ddsharpe** [comment]
jdk_8u802 is just the default value.  If you want to use the JDK 8u261 that you added to the cache, you need to specify the version on the command line like:
imagetool create --tag wls:12.2.1.4.0
--latestPSU --version 12.2.1.4.0 --jdkVersion 8u261
--user XXXX@oracle.com
--passwordFile passwd.txt

**Comment by eugsim1** [comment]
correct i have setup the flag and its working fine 
thanks for the prompt answer
