### ISSUE TITLE
dryrun flag creates Dockerfile but wls.rsp is missing

### ISSUE THREAD

**Issue by eugsim1** [oracle/weblogic-image-tool#213]
Hello
i tried the dryrun flag the Dockerfile was generated but when i tried to run the docker image build the build failed because the .rsp file is missing would be possible to generate this file with the dryrun flag ? thanks eugene

**Comment by ddsharpe** [comment]
The Dockerfile generated on stdout is not sufficient to "build the image". The entire build context is needed to build the image.  The build context includes the response file, the installers, etc.  Like the regular run, the `--dryRun` cleans up after itself and that build context is deleted after it verify that it could create the temporary build context folder (and copy all the necessary files to it).  If you want to "save" that build context, add the option `--skipcleanup`.  For example, `imagetool create --tag d:1 --dryRun --skipcleanup`

**Comment by eugsim1** [comment]
👍
