### ISSUE TITLE
create image missing [section] to add rpm properly in the buid image

### ISSUE THREAD

**Issue by eugsim1** [oracle/weblogic-image-tool#214]
Hi
i tried to use the --additionalBuildCommands  add_build_commands.txt i want to add rpm in the beginning of the docker file or other relevant image related setting but this is not possible 
the first flag that i found is [before-jdk-install] but i wanted to add my section even before the Install Java
is there any way to do it ? i have to generate dry run docker files , modify them manually and build the whole thing insted of using the command line
do you have anything to help me  ?

**Comment by ddsharpe** [comment]
Added feature to next Sprint.

**Comment by eugsim1** [comment]
Hi i have created a simple workaround :

create docker file with dry run then create a additional section with my rpm "update" concatenate them into a single Docker fie and create the image
