### ISSUE TITLE
update fails as user shoud be oracle

### ISSUE THREAD

**Issue by eugsim1** [oracle/weblogic-image-tool#215]
update
--tag=${TARGET_NEW_IMAGE}:latest
--fromImage=${FROM_IMAGE}
--dryRun
--pull
--chown=oracle:root
--latestPSU
--user eXXXX
--passwordFile passwd.txt
EOF
cat build_args_update_from_image

imagetool @build_args_update_from_image 

hi the update on the docker image fails as user should be oracle and not root
how can i resolve this  ?
thanks

**Comment by ddsharpe** [comment]
Can you post your output from above but use --dryRun ?  I would like to see the generated Dockerfile.

**Comment by ddsharpe** [comment]
@eugsim1 I cannot reproduce this issue.  Please reopen and attach the Dockerfile from the --dryRun output if you are still having an issue.
