### ISSUE TITLE
Hooks to provide customized inputs

### ISSUE THREAD

**Issue by ddsharpe** [oracle/weblogic-image-tool#23]
Need more details on the requirements and use case.

A couple of things have come up in the last few days:
1.  Need a hook prior to WDT createDomain to allow adding files that can be used with the WDT model @@FILE@@ token. The password file should not be copied to the final image.
2.  Need a hook to modify the Oracle Home after install to add security providers, modify scripts, etc.
3.  Run custom scripts during WLS patching (per patch instructions)

**Comment by mriccell** [comment]
We need a hook so that the user can specify a script that gets executed during image creation to delete a specific file for example.  I will gather a concrete example.
