### ISSUE TITLE
chown oracle:root not permitted if SELinux is active

### ISSUE THREAD

**Issue by ashaver** [oracle/weblogic-image-tool#236]
https://github.com/oracle/weblogic-image-tool/blob/085c1845e537166792f6244a3bed5a85709a3cc7/imagetool/src/main/resources/docker-files/Create_Image.mustache#L257

The action chown to root is not permitted under SELINUX, making this dockerfile fail when a prior WLS image is passed in that has the RedHat-UBI as a base layer (or any other image that has SELINUX active).

Please see PR https://github.com/oracle/weblogic-image-tool/pull/237

**Comment by ashaver** [comment]
https://github.com/oracle/weblogic-image-tool/pull/237

**Comment by ddsharpe** [comment]
@ashaver I am unable to reproduce this with CentOS, RedHat UBI 7 or 8.  I do not see the chown failures as you describe.  Did you use `registry.access.redhat.com/ubi8/ubi:latest` or something else?

**Comment by ashaver** [comment]
I used ubi7-minimal to generate the java 8 server. I then used the Java 8 server to build WLS 12.2.1.4. Running that image through the WIT produced a templated dockerfile which caused the error.

**Comment by ashaver** [comment]
I'll work on some scripts to duplicate the problem.

**Comment by ddsharpe** [comment]
@ashaver any updates?

**Comment by ddsharpe** [comment]
Closed due to no response.  Please reopen if you have additional details on how to reproduce.
