### ISSUE TITLE
Imagetool including --recommendedPatches --latestPSU failed

### ISSUE THREAD

**Issue by Nico-DB** [oracle/weblogic-image-tool#238]
Hello Together,

I am currently trying to create a Patched image with the following command:
./imagetool.sh create --tag wls:12.2.1.4.0_psu --jdkVersion 8u261 --version 12.2.1.4.0 --recomme --user <my_user> --passwordFile ./pw.txt --wdtVersion 1.9.8 --wdtDomainHome /u01/oracle/user_projects/domains/base_domain --wdtModel=./simple-topology.yaml --wdtVariables=./domain.properties --chown oracle:oinstall --additionalBuildCommands additional_args --additionalBuildFiles adminpass.properties,adminuser.properties,boot.properties

And it fails with the following error:
[SEVERE ] Patch ID 28186730 has multiple versions, please retry the command using one of the available patch versions

I did perform it 5 Days again and it worked there.

I am using the latest Image and Deploying-tool:
./imagetool.sh -V
imagetool:1.9.7

./imagetool.sh cache listItems
Cache contents
cache.dir=/Users/nicoschmidt/cache
wdt_1.9.8=/Users/nicoschmidt/Downloads/imagetool/bin/./weblogic-deploy.zip
28186730_13.9.4.2.5=/Users/nicoschmidt/cache/p28186730_139425_Generic.zip
wls_12.2.1.4.0=/Users/nicoschmidt/Downloads/imagetool/bin/./fmw_12.2.1.4.0_wls_Disk1_1of1.zip
jdk_8u261=/Users/nicoschmidt/Downloads/imagetool/bin/./jdk-8u261-linux-x64.tar.gz

**Comment by ddsharpe** [comment]
@Nico-DB I am unable to replicate this issue.  Are you still having this problem?  If so, please enable debug logging and upload the log to this issue.  To enable debug logging, see instructions in https://github.com/oracle/weblogic-image-tool/blob/master/site/logging.md 

[laptop]:bin $ imagetool create --tag d:1 --jdkVersion 8u261 --version 12.2.1.4.0 --recommendedPatches --user <my credential> --passwordFile ./pass.txt --wdtDomainHome /u01/oracle/user_projects/domains/base_domain --wdtModel ~/Desktop/demo/my_domain.yaml --wdtVariables ~/Desktop/demo/my_domain1.10.properties --wdtArchive ~/Desktop/demo/my_domain.zip --chown oracle:oinstall 
[INFO   ] Image Tool build ID: 69551969-7dd2-4953-8d4b-d08a5841ee62
[INFO   ] Temporary directory used for docker build context: /Users/desharpe/wlsimgbuilder_temp1688726232977303823
[INFO   ] Copying /Users/desharpe/Downloads/server-jre-8u261-linux-x64.tar.gz to build context folder.
[INFO   ] Using middleware installers (wls) version 12.2.1.4.0
[INFO   ] Copying /Users/desharpe/Downloads/fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip to build context folder.
[INFO   ] Copying /Users/desharpe/dev/weblogic-deploy-tooling/installer/target/weblogic-deploy.zip to build context folder.
[INFO   ] Oracle WebLogic Server - locating latest recommended patches...
[INFO   ] Oracle WebLogic Server - found recommended patch 32253037 WLS PATCH SET UPDATE 12.2.1.4.201209
[INFO   ] Oracle WebLogic Server - found recommended patch 32148640 WEBLOGIC SAMPLES SPU 12.2.1.4.210119
[INFO   ] Oracle WebLogic Server - found recommended patch 31544353 ADR FOR WEBLOGIC SERVER 12.2.1.4.0 JULY CPU 2020
[INFO   ] Oracle Coherence - locating latest recommended patches...
[INFO   ] Oracle Coherence - found recommended patch 32124456 Coherence 12.2.1.4.7 Cumulative Patch using OPatch
[INFO   ] The recommended ADR patch was skipped for the WLS installer, use --patch 31544353 to apply this patch
[INFO   ] Validating patches
[INFO   ] Validated patch 32253037 for Oracle WebLogic Server 12.2.1.4.0
[INFO   ] Validated patch 32148640 for Oracle WebLogic Server 12.2.1.4.0
[INFO   ] Validated patch 32124456 for Oracle Coherence 12.2.1.4.0
[INFO   ] No patch conflicts detected
[INFO   ] Using patch 32253037_12.2.1.4.0 from cache: /Users/desharpe/cache/p32253037_122140_Generic.zip
[INFO   ] Using patch 32148640_12.2.1.4.0 from cache: /Users/desharpe/cache/p32148640_122140_Generic.zip
[INFO   ] Using patch 32124456_12.2.1.4.0 from cache: /Users/desharpe/cache/p32124456_122140_Generic.zip
[INFO   ] Requesting patch information for patch 28186730
[INFO   ] Using patch 28186730_13.9.4.2.5 from cache: /Users/desharpe/cache/p28186730_139425_Generic.zip
[INFO   ] docker cmd = docker build --no-cache --force-rm --tag d:1 /Users/desharpe/wlsimgbuilder_temp1688726232977303823
Sending build context to Docker daemon  782.5MB

**Comment by ddsharpe** [comment]
Closed due to no response.
