### ISSUE TITLE
--recommendedPatches includes Bugfix patches

### ISSUE THREAD

**Issue by Nico-DB** [oracle/weblogic-image-tool#239]
Hello Together,

while creating a new image via the Image-Tool using the --recommendedPatches I noticed that the following patches had been installed:

`

[INFO   ] Oracle WebLogic Server - locating latest recommended patches...
--
775 | [INFO   ] Oracle WebLogic Server - found recommended patch 32253037 WLS PATCH SET UPDATE 12.2.1.4.201209
776 | [INFO   ] Oracle WebLogic Server - found recommended patch 32148640 WEBLOGIC SAMPLES SPU 12.2.1.4.210119
777 | [INFO   ] Oracle WebLogic Server - found recommended patch 31544353 ADR FOR WEBLOGIC SERVER 12.2.1.4.0 JULY CPU 2020
778 | [INFO   ] Oracle Coherence - locating latest recommended patches...
779 | [INFO   ] Oracle Coherence - found recommended patch 32124456 Coherence 12.2.1.4.7 Cumulative Patch using OPatch
780 | [INFO   ] The recommended ADR patch was skipped for the WLS installer, use --patch 31544353 to apply this patch
781 | [INFO   ] Validating patches
782 | [INFO   ] Validated patch 32253037 for Oracle WebLogic Server 12.2.1.4.0
783 | [INFO   ] Validated patch 32148640 for Oracle WebLogic Server 12.2.1.4.0
784 | [INFO   ] Validated patch 32124456 for Oracle Coherence 12.2.1.4.0
785 | [INFO   ] No patch conflicts detected
786 | [INFO   ] Could not find key 32253037_12.2.1.4.0 in the cache for patch 32253037
787 | [INFO   ] Downloading patch 32253037...
788 | [INFO   ] Adding patch 32253037_12.2.1.4.0 to cache, path=/root/cache/p32253037_122140_Generic.zip
789 | [INFO   ] Could not find key 32148640_12.2.1.4.0 in the cache for patch 32148640
790 | [INFO   ] Downloading patch 32148640...
791 | [INFO   ] Adding patch 32148640_12.2.1.4.0 to cache, path=/root/cache/p32148640_122140_Generic.zip
792 | [INFO   ] Could not find key 32124456_12.2.1.4.0 in the cache for patch 32124456
793 | [INFO   ] Downloading patch 32124456...
794 | [INFO   ] Adding patch 32124456_12.2.1.4.0 to cache, path=/root/cache/p32124456_122140_Generic.zip
795 | [INFO   ] Requesting patch information for patch 28186730
796 | [INFO   ] Could not find key 28186730_13.9.4.2.5 in the cache for patch 28186730
797 | [INFO   ] Downloading patch 28186730...
798 | [INFO   ] Adding patch 28186730_13.9.4.2.5 to cache, path=/root/cache/p28186730_139425_Generic.zip

`

When looking up the patches in the oracle support page, some of them are defined as Bugfix patches. The documentation there clearly says: "Before applying the non-mandatory patches, ensure that you have the
exact symptoms described in the bug."

Is this just a general Information and does the image tool does really only install latest + security patches or is there some kind of issue?

**Comment by ddsharpe** [comment]
--recommendedPatches applies all bug fixes that the Oracle release management team have marked as "recommended".  Recommended patches will, almost, always include the quarterly PSU, plus any security fixes that did not make the cutoff for the PSU.  Also, there is a rare case when a PSU overlay patch is recommended as well.  I have only seen this a couple times, and it has always been a security fix.  Other than the samples security patch, 32148640, I do not see any one-off patches in list you posted.  Which patch(es) are you concerned about? @Nico-DB

**Comment by ddsharpe** [comment]
Closed due to no response.
