### ISSUE TITLE
imagetool create fails when adding wdt 1.9.9 when Oracle Home already exists

### ISSUE THREAD

**Issue by xxhoffmann** [oracle/weblogic-image-tool#243]
I've created a baseimage:1.0 which only contains jdk8u281 and weblogic slim 12.2.1.4.0 without any further config and without domains

$ imagetool cache listItems:
wdt_1.9.9=weblogic-deploy-tooling-1.9.9.zip

$ imagetool create --fromImage=baseimage:1.0 --tag dev17 --version 12.2.1.4.0 --wdtVersion 1.9.9 --wdtModel dev17.yaml --wdtVariables dev17.properties --wdtArchive dev17.zip --wdtDomainHome /u01/domainsdev17 --skipcleanup --wdtModelOnly --dryRun

[SEVERE ] In image baseimage:1.0, the Oracle Home already exists at location: /u01/oracle

**Comment by xxhoffmann** [comment]
sorry...my bad....have to use imagetool update and not create.

**Comment by ddsharpe** [comment]
and no need to use`--version` in the update for creating the domain.
