### ISSUE TITLE
imagetool.sh can't apply patches to "official images" from container-registry.oracle.com

### ISSUE THREAD

**Issue by m0un10** [oracle/weblogic-image-tool#248]
Below is the evidence of the issue and reproduce instruction.

Prove image and patch exist and are in the cache
```
docker inspect container-registry.oracle.com/middleware/weblogic:12.2.1.4 > image-details.txt
unzip -l p30922843_122140_Generic.zip > patch-details.txt
imagetool.sh cache listItems > cache-details.txt
```

Note: The above outputs attached to this issue.
[cache-details.txt](https://github.com/oracle/weblogic-image-tool/files/6098181/cache-details.txt)
[patch-details.txt](https://github.com/oracle/weblogic-image-tool/files/6098182/patch-details.txt)
[image-details.txt](https://github.com/oracle/weblogic-image-tool/files/6098183/image-details.txt)

Run image tool (using `imagetool:1.9.9`. the latest at time of reporting this issue.)
```
imagetool.sh update --fromImage container-registry.oracle.com/middleware/weblogic:12.2.1.4 --tag wls:12.2.1.3.4-30922843 --patches 30922843_12.2.1.4.0 --chown oracle:root
```

Observe error
```
[INFO   ] Image Tool build ID: a184f608-9f1e-4dfd-bc97-489f9d051191
[INFO   ] Temporary directory used for docker build context: /Users/xxxxxxxx/wlsimgbuilder_temp4876332372108406443
[INFO   ] Could not find key 28186730_0.0.0.0.0 in the cache for patch 28186730
[SEVERE ] An OPatch version could not be found in the cache store and you have not provided Oracle Support credentials. Please provide --user with one of the password options or populate the cache store manually.
```

Not sure why it is looking for 28186730 instead of 30922843???

Note: It completes without an error when i remove the `--patches` line but then it doesn't actually add any patches, obviously

```
[INFO   ] Image Tool build ID: 816b9674-1402-42ac-9e34-c7cf180fa38b
[INFO   ] Temporary directory used for docker build context: /Users/xxxxxxxx/wlsimgbuilder_temp5530991902551838267
[INFO   ] docker cmd = docker build --no-cache --force-rm --tag wls:12.2.1.3.4-30922843 --build-arg no_proxy=local,*.local,169.254/16,*.169.254/16 /Users/craigbarr/wlsimgbuilder_temp5530991902551838267
Sending build context to Docker daemon  4.608kB

Step 1/5 : FROM container-registry.oracle.com/middleware/weblogic:12.2.1.4 as final_build
 ---> 0ea2cd3b676e
Step 2/5 : USER root
 ---> Running in 8fc48fca6eb0
Removing intermediate container 8fc48fca6eb0
 ---> dc906c0b5afa
Step 3/5 : ENV OPATCH_NO_FUSER=true
 ---> Running in fad4ed987473
Removing intermediate container fad4ed987473
 ---> 515957a9ab45
Step 4/5 : LABEL com.oracle.weblogic.imagetool.buildid="816b9674-1402-42ac-9e34-c7cf180fa38b"
 ---> Running in 07cf5d85afaf
Removing intermediate container 07cf5d85afaf
 ---> d4e492a53d67
Step 5/5 : USER oracle
 ---> Running in 61245b9dbf99
Removing intermediate container 61245b9dbf99
 ---> cc121dd6ca27
Successfully built cc121dd6ca27
Successfully tagged wls:12.2.1.3.4-30922843
[INFO   ] Build successful. Build time=13s. Image tag=wls:12.2.1.3.4-30922843
```

**Comment by xiancao** [comment]
I can reproduce the issue.

**Comment by jshum2479** [comment]
28186730 is the Opatch's patch, each individual weblogic patch may require an updated Opatch version but you are running in offline mode.   So you either need 28186730_13.9.4.2.4 or 28186730_13.9.4.2.5 for your patch 30922843 downloaded and added to the cache.

**Comment by m0un10** [comment]
If I understand correctly, you are suggesting that the tool has a requirement for another patch which hasn't been downloaded yet. Is there anyway to get a list of dependent patches?

I added `--user <user> --password` to try to workaround the offline issue but it still fails.

```
[INFO   ] Image Tool build ID: e677177d-6fdf-400d-84ea-f0e8981b4bc5
[INFO   ] Temporary directory used for docker build context: /Users/xxxxxxxxx/wlsimgbuilder_temp954700275476400433
[INFO   ] Requesting patch information for patch 28186730
[INFO   ] Could not find key 28186730_13.9.4.2.5 in the cache for patch 28186730
[INFO   ] Downloading patch 28186730...
[INFO   ] Adding patch 28186730_13.9.4.2.5 to cache, path=/Users/xxxxxxxxx/cache/p28186730_139425_Generic.zip
[INFO   ] Updating OPatch in final image from version 13.9.4.2.1 to version 13.9.4.2.5
[INFO   ] Requesting patch information for patch 30922843
[INFO   ] Validating patches
[SEVERE ] status code: 302, reason phrase: Found
```

**Comment by jshum2479** [comment]
WebLogic uses Opatch to apply the weblogic patch.  When you downloaded the patch and unzip it, there is a README file that will tell you what opatch version is needed to apply that particular patch.  Sometimes the default version that came with the oracle home installation is out of date or that particular patch may need a specific version of opatch to be used.  If you are using online mode where you specify user name and password, the tool will figure out the dependency for you. 

Unfortunately,  there is a recent change in the support system, we discovered a problem with validating patch conflicts calls against the support system.  It has been identified but waiting to be merge and release.

**Comment by ddsharpe** [comment]
@m0un10 Once you have downloaded the OPatch version with the credentials, you should be able to run offline again because that ZIP for OPatch is now cached.  I just ran your imagetool command with the new 1.9.10 release and it completed successfully.  If you are still having an issue while trying 1.9.10, please let me know and send me the debug log (enabled by changing the settings in `logging.properties`).

**Comment by m0un10** [comment]
@ddsharpe would you like to share the exact command you ran?

I'm still getting the same issue that i reported [here](https://github.com/oracle/weblogic-image-tool/issues/248#issuecomment-793193634). I suspect you'll get the same with `imagetool.sh update --fromImage container-registry.oracle.com/middleware/weblogic:12.2.1.4 --tag wls:12.2.1.3.4-30922843 --patches 30922843_12.2.1.4.0 --chown oracle:root --user <yourUser> --password <yourPassword>`

**Comment by m0un10** [comment]
Apologies, I just realised you released a new version. Upon upgrade from 1.9.9 to 1.9.10, it is now possible to apply patches to "official images" from container-registry.oracle.com.
