### ISSUE TITLE
WIT 'WDT mode' doesn't set executable permissions on WDT scripts unless a model file is also specified

### ISSUE THREAD

**Issue by tbarnes-us** [oracle/weblogic-image-tool#250]
_Minor bug:_ 

When I use WIT to create an image with WDT installed, but don't actually include a model via `--wdtModel`, then the WDT scripts in the image aren't marked executable (they're just `rw`, not `rwx`).  This of course fails later attempts to call `createDomain.sh`.

_The work-around is to supply a dummy model, for example:_

```
echo "" > ./empty-model.yaml
$WORKDIR/tooling/imagetool/bin/imagetool.sh update \
  --fromImage container-registry.oracle.com/middleware/weblogic:12.2.1.4 \
  --wdtModel ./empty-model.yaml \
  --wdtModelOnly \
  --wdtDomainType WLS \
  --chown oracle:root \
  --tag model-in-image-is:cool
```

**Comment by ddsharpe** [comment]
Fixed in 5c38f0994454d0b04073d2b25b4ab7ccdece780b for release 1.9.10
