### ISSUE TITLE
Question about Enterprise Manager Cloud Control

### ISSUE THREAD

**Issue by textanalyticsman** [oracle/weblogic-image-tool#251]
Hello,

Is there any official image to deploy Enterprise Manager Cloud Control on containers?

Best regards,
TAM

**Comment by ddsharpe** [comment]
@textanalyticsman This question is probably better asked on the public slack channel.  But, @mriccell might know.

**Comment by mriccell** [comment]
OEM does not have certified on containers, I believe it is in their roadmap.
