### ISSUE TITLE
java.io.IOException: Build command failed with error: Error: unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by avianabr** [oracle/weblogic-image-tool#267]
i am trying to implement the mii_sample, but when I run the imagetool.sh update command I got the following error

[opc@master1 model-images]$ ./imagetool/bin/imagetool.sh update \
>   --tag model-in-image:WLS-v1 \
>   --fromImage container-registry.oracle.com/middleware/weblogic:12.2.1.4 \
>   --wdtModel      ./model-in-image__WLS-v1/model.10.yaml \
>   --wdtVariables  ./model-in-image__WLS-v1/model.10.properties \
>   --wdtArchive    ./model-in-image__WLS-v1/archive.zip \
>   --wdtModelOnly \
>   --wdtDomainType WLS \
>   --chown oracle:root
[FINER  ] Entering UpdateImage.call 
[FINER  ] ENTRY 565e5319-b21a-4fa1-9665-3362a9e444ca
[INFO   ] WebLogic Image Tool version 1.9.12
[INFO   ] Image Tool build ID: 565e5319-b21a-4fa1-9665-3362a9e444ca
[FINER  ] RETURN
[INFO   ] Temporary directory used for image build context: /home/opc/wlsimgbuilder_temp3036036544344918558
[FINER  ] ENTRY docker container-registry.oracle.com/middleware/weblogic:12.2.1.4 /probe-env/test-update-env.sh /home/opc/wlsimgbuilder_temp3036036544344918558
[FINER  ] ENTRY [docker, run, --rm, container-registry.oracle.com/middleware/weblogic:12.2.1.4, /bin/bash, -c, echo IyEvdXNyL2Jpbi9lbnYgYmFzaAojCiNDb3B5cmlnaHQgKGMpIDIwMTksIDIwMjEsIE9yYWNsZSBhbmQvb3IgaXRzIGFmZmlsaWF0ZXMuCiMKI0xpY2Vuc2VkIHVuZGVyIHRoZSBVbml2ZXJzYWwgUGVybWlzc2l2ZSBMaWNlbnNlIHYgMS4wIGFzIHNob3duIGF0IGh0dHBzOi8vb3NzLm9yYWNsZS5jb20vbGljZW5zZXMvdXBsLgojCgppZiBbWyAtZiAvZXRjL29zLXJlbGVhc2UgXV07IHRoZW4KICBjYXQgL2V0Yy9vcy1yZWxlYXNlIHwgZ3JlcCAtb0UgJ15JRD1bXCJdPyhcdyspW1wiXT8nCiAgY2F0IC9ldGMvb3MtcmVsZWFzZSB8IGdyZXAgLW9FICdeVkVSU0lPTl9JRD1bXCJdP1tbOmRpZ2l0Ol1cLl0rW1wiXT8nCmZpCgppZiBjb21tYW5kIC12IGRuZiAmPiAvZGV2L251bGw7IHRoZW4KICBlY2hvIFBBQ0tBR0VfTUFOQUdFUj1ETkYKZWxpZiBjb21tYW5kIC12IHl1bSAmPiAvZGV2L251bGw7IHRoZW4KICBlY2hvIFBBQ0tBR0VfTUFOQUdFUj1ZVU0KZWxpZiBjb21tYW5kIC12IG1pY3JvZG5mICY+IC9kZXYvbnVsbDsgdGhlbgogIGVjaG8gUEFDS0FHRV9NQU5BR0VSPU1JQ1JPRE5GCmVsaWYgY29tbWFuZCAtdiBhcHQtZ2V0ICY+IC9kZXYvbnVsbDsgdGhlbgogIGVjaG8gUEFDS0FHRV9NQU5BR0VSPUFQVEdFVAplbGlmIGNvbW1hbmQgLXYgYXBrICY+IC9kZXYvbnVsbDsgdGhlbgogIGVjaG8gUEFDS0FHRV9NQU5BR0VSPUFQSwplbGlmIGNvbW1hbmQgLXYgenlwcGVyICY+IC9kZXYvbnVsbDsgdGhlbgogIGVjaG8gUEFDS0FHRV9NQU5BR0VSPVpZUFBFUgpmaQoKaWYgW1sgLW4gIiRKQVZBX0hPTUUiIF1dOyB0aGVuCiAgZWNobyBKQVZBX0hPTUU9IiRKQVZBX0hPTUUiCiAgZWNobyBKQVZBX1BBVEg9IiQocmVhZGxpbmsgLWYgJEpBVkFfSE9NRSkiCmZpCgppZiBbWyAtbiAiJE9SQUNMRV9IT01FIiBdXTsgdGhlbgogIGVjaG8gT1JBQ0xFX0hPTUU9IiRPUkFDTEVfSE9NRSIKICBXTFNfVFlQRT0kKGNhdCAiJE9SQUNMRV9IT01FIi9pbnZlbnRvcnkvcmVnaXN0cnkueG1sIDI+IC9kZXYvbnVsbCB8IGdyZXAgLXEgJ1dlYkxvZ2ljIFNlcnZlciBmb3IgRk1XJyAmJiBwcmludGYgImZtdyIpCiAgaWYgW1sgLW4gIiRXTFNfVFlQRSIgXV07IHRoZW4KICAgIGVjaG8gV0xTX1RZUEU9IiRXTFNfVFlQRSIKICBmaQogIGlmIFtbIC1uICIkSkFWQV9IT01FIiBdXTsgdGhlbgogICAgZWNobyBXTFNfVkVSU0lPTj0iJCgiJEpBVkFfSE9NRSIvYmluL2phdmEgLWNwICIkT1JBQ0xFX0hPTUUiL3dsc2VydmVyL3NlcnZlci9saWIvd2VibG9naWMuamFyIHdlYmxvZ2ljLnZlcnNpb24gMj4gL2Rldi9udWxsIHwgZ3JlcCAtb0UgLW0gMSAnKFtbOmRpZ2l0Ol1cLl0rKScgfCBoZWFkIC0xKSIKICBmaQogIGVjaG8gT1BBVENIX1ZFUlNJT049IiQoIiRPUkFDTEVfSE9NRSIvT1BhdGNoL29wYXRjaCB2ZXJzaW9uIDI+IC9kZXYvbnVsbCB8IGdyZXAgLW9FIC1tIDEgJyhbWzpkaWdpdDpdXC5dKyknKSIKICAiJE9SQUNMRV9IT01FIi9PUGF0Y2gvb3BhdGNoIGxzaW52ZW50b3J5ID4gL3RtcC9sc291dCAyPiAvZGV2L251bGwKCiAgZWNobyBPUkFDTEVfSE9NRV9VU0VSPSIkKHN0YXQgLWMgJyVVJyAiJE9SQUNMRV9IT01FIikiCiAgZWNobyBPUkFDTEVfSE9NRV9HUk9VUD0iJChzdGF0IC1jICclRycgIiRPUkFDTEVfSE9NRSIpIgoKICBpZiBbWyAgLWYgIi90bXAvbHNvdXQiIF1dOyB0aGVuCiAgICBlY2hvIExTSU5WX1RFWFQ9IiQoYmFzZTY0IC13IDAgL3RtcC9sc291dCkiCiAgZmkKZmkKCmlmIFtbIC1uICIkRE9NQUlOX0hPTUUiIF1dOyB0aGVuCiAgZWNobyBET01BSU5fSE9NRT0iJERPTUFJTl9IT01FIgogIGlmIFtbICEgLWQgIiRET01BSU5fSE9NRSIgXV0gfHwgW1sgLXogIiQobHMgLUEgJERPTUFJTl9IT01FKSIgXV07IHRoZW4KICAgIGVjaG8gV0RUX01PREVMX09OTFk9VFJVRQogIGZpCmZpCgppZiBbWyAtbiAiJFdEVF9NT0RFTF9IT01FIiBdXTsgdGhlbgogIGVjaG8gV0RUX01PREVMX0hPTUU9IiRXRFRfTU9ERUxfSE9NRSIKZmk= | base64 -d | /bin/bash]
[FINER  ] ENTRY
[FINER  ] ENTRY [docker, image, prune, -f, --filter, label=com.oracle.weblogic.imagetool.buildid=565e5319-b21a-4fa1-9665-3362a9e444ca]
java.io.IOException: Build command failed with error: Error: unknown shorthand flag: 'f' in -f

	at com.oracle.weblogic.imagetool.util.Utils.processError(Utils.java:289)
	at com.oracle.weblogic.imagetool.util.Utils.runDockerCommand(Utils.java:267)
	at com.oracle.weblogic.imagetool.util.Utils.removeIntermediateDockerImages(Utils.java:749)
	at com.oracle.weblogic.imagetool.cli.menu.UpdateImage.call(UpdateImage.java:173)
	at com.oracle.weblogic.imagetool.cli.menu.UpdateImage.call(UpdateImage.java:31)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at com.oracle.weblogic.imagetool.cli.ImageTool.run(ImageTool.java:89)
	at com.oracle.weblogic.imagetool.cli.ImageTool.main(ImageTool.java:56)

**Comment by ddsharpe** [comment]
@ avianabr It would appear that you have a very old version of Docker installed.  Can you run `docker --version` and reply with the result?  But if you prefer, you can try upgrading to a newer version of Docker such as 20.10.5.

**Comment by ddsharpe** [comment]
Closed due to lack of response.
