### ISSUE TITLE
'imagetool cache addPatch' is not able to find some patches on Oracle Support

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#27]
I'm using the tool `imagetool cache addPatch` to prepare patches for WebLogic Server, but the tool is able to add only some of them.

For example, it works correctly for adding the latest PSU for WLS. Here is the full command that I run to achieve that:
```
$ imagetool cache addPatch \
    --type wls \
    --version 12.2.1.3.0 \
    --patchId p29016089 \
    --path "${CACHE_DIR}/p29016089_122130_Generic.zip" \
    --user ${ORACLE_SUPPORT_USER} \
    --password ${ORACLE_SUPPORT_PASSWORD}
[2019-06-14 15:53:35] [com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry] [INFO   ] Added Patch entry 29016089_12.2.1.3.0=/tmp/weblogic-image-tool-cache/p29016089_122130_Generic.zip for wls
```

But then I try to add some patches like the latest OPatch or [the patch 26045997](https://support.oracle.com/epmos/faces/PatchResultsNDetails?patchId=26045997) for example, and the command fails indicating that it was not found in Oracle Support. The full command for adding the patch `26045997` and its output is the following:
```
$ imagetool cache addPatch \
    --type wls \
    --version 12.2.1.3.0 \
    --patchId p26045997 \
    --path "${CACHE_DIR}/p26045997_122130_Generic.zip" \
    --user ${ORACLE_SUPPORT_USER} \
    --password ${ORACLE_SUPPORT_PASSWORD}
[2019-06-14 16:06:10] [com.oracle.weblogic.imagetool.cli.CLIDriver] [SEVERE ] Response code: -1, message: Unable to find patchId p26045997 on Oracle Support
```

**Comment by jshum2479** [comment]
This is a known issue, the verification logic assume the product is weblogic server but for your case is Oracle JDBC for Fusion Middleware 12.2.1.3.0.  We will remove the verification.

**Comment by lukasged** [comment]
ok, thanks. For us it's fine if the verification is removed.

**Comment by jshum2479** [comment]
We have completely revamp the patching process, please retry with the latest branch:

1.  The 26045997 is not a weblogic patch, so the opatch will not work, but the good news is - that patch is included in the default installer, so there is really no need to apply it.  There are couple other similar to this
2.  When adding patch manually, you only have to provide the patchId and path.  The format of the patchId is 99999999_99.9.9.9.999999 .  For example,

```29135930_12.2.1.3.190416=/home/user/cache/p29135930_12213190416_Generic.zip
```
Note: there is no 'p' anymore,  the first 8 digits are the patch number followed by a underscore and then the release number.   The release number is the value shown in the support.oracle.com -> patches&update -> search for patch name or number -> 

The resulting page has the release number in the release column.   Then, when applying patch in create or update, you can specify the entire key for patchId, such as ```29135930_12.2.1.3.190416``` in this example.

Please let us know if you run into any issue, thanks.
