### ISSUE TITLE
Building Image (docker build) Error :: <WLSDPLY-20008> <createDomain argument processing failed: Supplied Domain Home directory /u01/oracle/user_projects/domains/base_domain was not valid

### ISSUE THREAD

**Issue by danielrpgj31** [oracle/weblogic-image-tool#275]
Hi, i am trying execute the sample, but i am getting WLSDPLY-20008 createDomain error.
Please, see the steps attached.
[weblogic+kubernetes+WDT.txt](https://github.com/oracle/weblogic-image-tool/files/6503379/weblogic%2Bkubernetes%2BWDT.txt)

Regards, 

Daniel Ribeiro.

**Comment by ddsharpe** [comment]
In your attached TXT, you are retrieving a VERY VERY old version of the tool
wget https://github.com/oracle/weblogic-deploy-tooling/releases/download/weblogic-deploy-tooling-0.11/weblogic-deploy.zip

The current release is 1.9.12. (You downloaded a version from Jun 2018).  Please try again with the latest release.
