### ISSUE TITLE
Could the tool assume that the `--fromImage` image includes JDK?

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#28]
Currently, the `imagetool create` tool will build a Docker image that will install a desired version of JDK during its building process.

Would it be possible for the tool to assume that the base Docker image provided as `--fromImage` already comes with an installation of JDK, and use its environment variable `JAVA_HOME` for locating the Java binaries and running Java commands?

**Comment by ddsharpe** [comment]
Yes, we will add this feature soon.

**Comment by lukasged** [comment]
That´s great, thanks!
