### ISSUE TITLE
cache addPatch prefixes Patch with "null_12.2.1.3.0"

### ISSUE THREAD

**Issue by DirkNachbar** [oracle/weblogic-image-tool#34]
Hi,

after I have created a Docker Image with imagetool, the imagetool were adding the lastPSU correctly to the imagetool cache, but the patch is prefixed with "null_12.2.1.3.0".

```
imagetool cache listItems
Cache contents
cache.dir=/home/user/cache
jdk_8u211=/work/software/jdk-8u211-linux-x64.tar.gz
null_12.2.1.3.0=/home/user/cache/p29016089_122130_Generic.zip
wls_12.2.1.3.0=/work/software/fmw_12.2.1.3.0_wls_Disk1_1of1.zip
28186730_opatch=/home/user/cache/p28186730_139400_Generic.zip
29921455_12.2.1.3.0=/work/software/p29921455_12213190416_Generic.zip
```
the OPatch Patch p28186730_139400_Generic.zip is correctly prefixed with ```28186730_opatch```, but the latest PSU p29016089_122130_Generic.zip is prefixed with ```null_12.2.1.3.0```
Would be cool, if you could display the Patch Number instead of null.

Cheers

Dirk

**Comment by ddsharpe** [comment]
@jshum2479 Please review that this is fixed with your latest changes to the caching and update this issue with the PR# and close.

**Comment by jshum2479** [comment]
This is resolved in the master branch.  Please try it out,  it is a good idea to modify the .metafile  to delete the null_12.2.1.3.0 entry.

**Comment by DirkNachbar** [comment]
I have tested it and it works like charm, many thanks

Cheers
Dirk
