### ISSUE TITLE
While creating Image using WDT discover yaml file, getting createDomain failed to set Password: invalid password.

### ISSUE THREAD

**Issue by manoj4527** [oracle/weblogic-image-tool#365]
Type help() for help on available commands

####<Jul 27, 2022 10:30:03 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 2.3.2:.229089c:Jul 20, 2022 15:29 UTC>
####<Jul 27, 2022 10:30:04 AM> <INFO> <XPathUtil> <getPSU> <> <No patches home at /u01/oracle/inventory/patches>
####<Jul 27, 2022 10:30:05 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /u01/wdt/weblogic-deploy/lib/model_filters.json>
####<Jul 27, 2022 10:30:05 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20016> <No filters of type create found in filter configuration file /u01/wdt/weblogic-deploy/lib/model_filters.json>
####<Jul 27, 2022 10:30:11 AM> <INFO> <DomainCreator> <__create_domain> <WLSDPLY-12203> <Creating domain of type WLS>
####<Jul 27, 2022 10:30:11 AM> <INFO> <DomainCreator> <__create_base_domain_with_select_template> <WLSDPLY-12210> <Selecting base template named Basic WebLogic Server Domain>
####<Jul 27, 2022 10:30:19 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12212> <Loading selected templates>
####<Jul 27, 2022 10:30:42 AM> <INFO> <DomainCreator> <__set_domain_name> <WLSDPLY-12227> <Changing domain name from base_domain to agbanking>

Issue Log for createDomain version 2.3.2 running WebLogic version 14.1.1.0.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-12409: createDomain failed to create the domain: Failed to set attribute Password in path /Security/agbanking/User/weblogic to value <masked>: 60455: Invalid password.
60455: The password must be at least 8 alphanumeric characters with at least one number or special character.
60455: Correct the password.

Total:       WARNING :     0    SEVERE :     1

[SEVERE ] Build command failed with error: Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

(microdnf:2): libdnf-WARNING **: 10:18:55.266: failed to setup monitor: Unable to find default local file monitor type

(microdnf:2): libdnf-WARNING **: 10:18:55.267: failed to setup monitor: Unable to find default local file monitor type

(microdnf:2): libdnf-WARNING **: 10:18:55.267: failed to setup monitor: Unable to find default local file monitor type

(microdnf:39): libdnf-WARNING **: 10:20:08.574: failed to setup monitor: Unable to find default local file monitor type

(microdnf:39): libdnf-WARNING **: 10:20:08.574: failed to setup monitor: Unable to find default local file monitor type

(microdnf:39): libdnf-WARNING **: 10:20:08.574: failed to setup monitor: Unable to find default local file monitor type

(microdnf:1): libdnf-WARNING **: 10:20:14.996: failed to setup monitor: Unable to find default local file monitor type

(microdnf:1): libdnf-WARNING **: 10:20:14.996: failed to setup monitor: Unable to find default local file monitor type

(microdnf:1): libdnf-WARNING **: 10:20:14.996: failed to setup monitor: Unable to find default local file monitor type
####<Jul 27, 2022 10:30:43 AM> <SEVERE> <create> <main> <WLSDPLY-12409> <createDomain failed to create the domain: Failed to set attribute Password in path /Security/agbanking/User/weblogic to value <masked>: 60455: Invalid password.
60455: The password must be at least 8 alphanumeric characters with at least one number or special character.
60455: Correct the password.>
createDomain.sh failed (exit code = 2)

=========
cat DiscoveredDemoDomain01.yaml
domainInfo:
    AdminUserName: '@@PROP:AdminUserName@@'
    AdminPassword: '@@PROP:AdminPassword@@'
topology:
    Name: agbanking
    ProductionModeEnabled: true
    DomainVersion: 14.1.1.0.0
    NMProperties:
        PropertiesVersion: 14.1.1.0.0
        JavaHome: /u01/oracle/jdk1.8.0_271
        weblogic.StartScriptName: startWebLogic.sh
    Server:
        AdminServer:
            ListenAddress: 0.0.0.0
            SSL:
                Enabled: true
                ListenPort: 7501
        MS-1:
            Machine: Machine-1
            ListenPort: 8001
            WebServer:
                WebServerLog:
                    NumberOfFilesLimited: false
        MS-2:
            Machine: Machine-1
            ListenPort: 8002
            WebServer:
                WebServerLog:
                    NumberOfFilesLimited: false
    Machine:
        Machine-1: {}
    SecurityConfiguration:
        NodeManagerUsername: '@@PROP:SecurityConfig.NodeManagerUsername@@'
        NodeManagerPasswordEncrypted: '@@PROP:SecurityConfig.NodeManagerPasswordEncrypted@@'
        Realm:
            myrealm:
                CertPathBuilder: WebLogicCertPathProvider
============
DiscoverDemoDomain.properties
AdminPassword=weblogic
AdminUserName=weblogic2$
SecurityConfig.NodeManagerPasswordEncrypted=weblogic2$
SecurityConfig.NodeManagerUsername=c5aB9ULUIp
===========

**Comment by ddsharpe** [comment]
I have been unable to reproduce this error in 14.1.1.  I simplified the use case down to the user that the error message is complaining about.  Please try the model and properties (below) and report results.  I tested with 14.1.1 and 12.2.1.4, but no errors were reported in either.

**test.properties
---------**
```
mypass=welcome2$
```

**test.yaml
----------**
```
domainInfo:
    AdminUserName: weblogic
    AdminPassword: '@@prop:mypass@@'
topology:
    Name: testme
```

**Comment by ddsharpe** [comment]
Closing due to lack of response.  Please re-open this issue if the error is reproduced and additional information can be provided.
