### ISSUE TITLE
error: Get "https://ghcr.io/v2/ while creating weblogic image

### ISSUE THREAD

**Issue by dbibiamine-gh** [oracle/weblogic-image-tool#423]
Hello,

Im facing an error during the creation of : imagetool create --tag wls:12.2.1.3.0

[SEVERE ] Build command failed with error: Get "https://ghcr.io/v2/": proxyconnect tcp: dial tcp: lookup proxy.example

My imagetool version imagetool:1.11.9

Thnaks

**Comment by ddsharpe** [comment]
Can you execute a docker pull of the base image?  Such as: $ docker pull ghcr.io/oracle/oraclelinux:8-slim
Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by dbibiamine-gh** [comment]
> Can you execute a docker pull of the base image? Such as:
> 
> ```
> $ docker pull ghcr.io/oracle/oraclelinux:8-slim
> Error response from daemon: Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> ```
> 
> or does your pull request fail like this? If so, your proxy may not be configured correctly for docker (or a firewall is blocking you). I have the same problem and had to drop off the corporate network to see if this was a GitHub issue or internal (GitHub was working just fine).

it works, but when i try to pull oracle/weblogic:12.2.1.3.0 it's Fail

**Comment by rjeberhard** [comment]
> it works, but when i try to pull oracle/weblogic:12.2.1.3.0 it's Fail
