### ISSUE TITLE
mvn package fails with file not found

### ISSUE THREAD

**Issue by scanlonjts** [oracle/weblogic-image-tool#45]
Running com.oracle.weblogic.imagetool.impl.meta.FileCacheStoreTest
java.io.IOException: Cache Directory does not exists /Users/xxxxx/cache

did not see that dir listed as dependency - should be either added to teh docs as needing to be manually created OR mvn process should create OR cache should not be in user home dir but should be in project dir (and in .gitignore)

**Comment by ddsharpe** [comment]
I am looking into this.  The new integration tests caused this behavior.  For now, use "package", like "mvn clean package".

**Comment by ddsharpe** [comment]
Fixed by #47
