### ISSUE TITLE
Azure ACR build support

### ISSUE THREAD

**Issue by jkramplify** [oracle/weblogic-image-tool#453]
Since its not possible anymore to run docker in kubernetes, does weblogic-image-tool support az acr build?

**Comment by ddsharpe** [comment]
@jkramplify Since Image Tool is a build time tool, what does not running Docker in Kubernetes have to do with this tool?

WebLogic Image Tool could be made to support Azure's container registry build tool, but today is only tested with Podman and Docker.

**Comment by jkramplify** [comment]
Hi @ddsharpe apologies for not giving more information. But anyway I found what I need from the docs I don't know why I missed this. The option I'm looking for is the --builder parameter.
