### ISSUE TITLE
inspect returns no information

### ISSUE THREAD

**Issue by arnabold** [oracle/weblogic-image-tool#465]
Using Rancher Desktop 1.9.1 on Windows 11 in a OracleLinux_8_5 WSL distro, inspect returns no info. The image is available locally.

```
$ imagetool --version
imagetool:1.11.11

$ docker inspect container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
[
    {
        "Id": "sha256:89e756943fb856423496d3363a6e674b690a307499cc867a7ba2479a4df4c793",
...

$ imagetool inspect -i container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714 --patches
[INFO   ] Inspecting container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714, this may take a few minutes if the image is not available locally.
{
  "os" : {
    "id" : "null",
    "name" : "null",
    "version" : "null"
  },
}
```

**Comment by ddsharpe** [comment]
I am unable to replicate your case. However, when I pulled the image just now, the ID for the image is not the same as what you have.  Please try to re-pull from container-registry and see if you get the image IDs as I did (see below).

`[laptop]:~ $ docker pull container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
12.2.1.4-generic-jdk8-ol7-230714: Pulling from middleware/weblogic_cpu
2c4d20451a29: Pull complete 
b464257b7dbf: Pull complete 
6fc4f526503d: Pull complete 
6cc7af28512a: Pull complete 
ce2db17de7f8: Pull complete 
8371f43ff555: Pull complete 
Digest: sha256:dbbb16cd44d1dc19712b2728126b8b4d4e5b2c45e3853cbf805f42431035ceb1
Status: Downloaded newer image for container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
[laptop]:~ $ docker inspect container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
[
    {
        "Id": "sha256:a5157cf33a8db67353de329336edd47a4f91b12f3ddad544867a901c563155e7",
        "RepoTags": [
            "container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714"
        ],
`
After which, I am able to run imagetool inspect.

`[laptop]:bin $ imagetool inspect -i container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714
[INFO   ] Inspecting container-registry.oracle.com/middleware/weblogic_cpu:12.2.1.4-generic-jdk8-ol7-230714, this may take a few minutes if the image is not available locally.
{
  "os" : {
    "id" : "ol",
    "name" : "Oracle Linux Server",
    "version" : "7.9",
    "releasePackage" : "oraclelinux-release-7.9-1.0.11.el7.aarch64"
  },
  "javaHome" : "/u01/jdk",
  "javaVersion" : "1.8.0_381",
  "oracleHome" : "/u01/oracle",
  "oracleHomeGroup" : "root",
  "oracleHomeUser" : "oracle",
  "oracleInstalledProducts" : "WLS,COH,TOPLINK",
  "packageManager" : "YUM",
  "wlsVersion" : "12.2.1.4.0"
}`

**Comment by ddsharpe** [comment]
Sorry, I confused myself by pulling the ARM image first.  After switching to the amd64 image, the image ID matched up.  If you need to debug further, please enable debug logging and upload the log file.  See https://oracle.github.io/weblogic-image-tool/userguide/logging/

**Comment by ddsharpe** [comment]
closing due to lack of response
