### ISSUE TITLE
Invalid Oracle support credentials

### ISSUE THREAD

**Issue by Nico-DB** [oracle/weblogic-image-tool#473]
Since a couple of days we do receive the following error while performing the imaging-tool:

bash imagetool.sh create --tag "${IMAGE_REPO_NAME}:${WEBLOGIC_VERSION}-domain-app" --jdkVersion $jdkFolder --version $WEBLOGIC_VERSION --latestPSU --recommendedPatches --patches=${WEBLOGIC_OVERLAY_PATCHES} --user $oracleSupportUser --passwordFile $path/pw.txt --wdtVersion $deploytoolRelease --wdtDomainHome /u01/oracle/user_projects/domains/base_domain --wdtArchive ./archive.zip --wdtModel=$path/simple-topology-with-application.yaml --wdtVariables=$path/domain.properties --chown oracle:oinstall --additionalBuildCommands $path/additional_args --additionalBuildFiles $path/adminpass.properties,$path/adminuser.properties,$path/boot.properties
--

767 | Building the Weblogic Image without using any overlaypatches
768 | Creating weblogic image without test-application
769 | [INFO   ] WebLogic Image Tool version 1.12.1
770 | [INFO   ] Image Tool build ID: bbc28031-46ff-440f-9d02-41c158d16254
771 | [INFO   ] Temporary directory used for image build context: /root/wlsimgbuilder_temp667641210498351098
772 | [INFO   ] Copying /codebuild/output/src3333965679/src/codebuild/adminpass.properties to build context folder.
773 | [INFO   ] Copying /codebuild/output/src3333965679/src/codebuild/adminuser.properties to build context folder.
774 | [INFO   ] Copying /codebuild/output/src3333965679/src/codebuild/boot.properties to build context folder.
775 | [SEVERE ] Invalid Oracle support credentials, verify the values provided for user and password match your OTN credential
776 | Something went wrong while creating the Weblogic Docker Image!

I have used the exact same credentials to login at support.oracle.com and it worked. Last week everything worked.

**Comment by ddsharpe** [comment]
@Nico-DB I am not seeing any credential issues when I try it.  If you are available to reach out to me on Slack, I can try to help you look at your environment to see if there is something wrong there.  Or, you can turn on debug logging and upload the log here or on Slack.  See https://oracle.github.io/weblogic-image-tool/userguide/logging/

**Comment by ddsharpe** [comment]
@Nico-DB Another way to test your credential would be to use `wget`.  Save your username and password to environment variables and pass them to wget.  And assuming wget succeeds, pass the same environment variables to imagetool.  If wget succeeds and imagetool fails, there is probably a bug with imagetool.
```
wget --user $MY_USERID --password $MY_PASS https://updates.oracle.com/Orion/Services/metadata?table=aru_languages -O output.txt
```

**Comment by ddsharpe** [comment]
@Nico-DB Oracle reported an outage of some customer credentials that started Sunday night across all patching services, but is resolved now.  If you are still experiencing issues, please reopen this issue.
