### ISSUE TITLE
Error when downloading updates from Oracle

### ISSUE THREAD

**Issue by Tobias-DB** [oracle/weblogic-image-tool#474]
The Image-Tool fails to download certain patch files from https://updates.oracle.com/Orion/Services/download/p28186730_1394214_Generic.zip?aru=25360527&patch_file=p28186730_1394214_Generic.zip

The error seems to be occuring for quite some time now.

please see the error message below:

`

Building the Weblogic Image without using any overlaypatches
--
626 | Creating weblogic image without test-application
627 | [INFO   ] WebLogic Image Tool version 1.12.1
628 | [INFO   ] Image Tool build ID: 88f2c4ff-2789-48a2-a925-3a8708241f1b
629 | [INFO   ] Temporary directory used for image build context: /root/wlsimgbuilder_temp2527739473598158739
630 | [INFO   ] Copying /codebuild/output/src1929607424/src/codebuild/adminpass.properties to build context folder.
631 | [INFO   ] Copying /codebuild/output/src1929607424/src/codebuild/adminuser.properties to build context folder.
632 | [INFO   ] Copying /codebuild/output/src1929607424/src/codebuild/boot.properties to build context folder.
633 | [INFO   ] Copying /codebuild/output/src1929607424/src/codebuild/jdk-11.0.21_linux-x64_bin.tar.gz to build context folder.
634 | [INFO   ] Using middleware installers (wls) version 14.1.1.0.0
635 | [INFO   ] Copying /codebuild/output/src1929607424/src/codebuild/fmw_14.1.1.0.0_wls_Disk1_1of1.zip to build context folder.
636 | [INFO   ] Oracle JDBC for Fusion Middleware - locating latest recommended patches...
637 | [INFO   ] Failed to get response from patches server, Read timed out, retrying [1/10]
638 | [INFO   ] Failed to get response from patches server, Read timed out, retrying [1/10]
639 | [INFO   ] Failed to get response from patches server, Read timed out, retrying [2/10]
640 | [INFO   ] Oracle JDBC for Fusion Middleware - found recommended patch 32720458 Fix for Bug 32720458
641 | [INFO   ] FMW Platform - locating latest recommended patches...
642 | [INFO   ] Version 14.1.1.0.0 did not contain FMW Platform, skipping
643 | [INFO   ] Middleware Common Libraries and Tools - locating latest recommended patches...
644 | [INFO   ] Middleware Common Libraries and Tools - found recommended patch 35671007 RDA release 23.4-20231017 for FMW 14.1.1.0.0
645 | [INFO   ] Oracle WebLogic Server - locating latest recommended patches...
646 | [INFO   ] Oracle WebLogic Server - found recommended patch 35904051 WLS PATCH SET UPDATE 14.1.1.0.231012
647 | [INFO   ] Oracle WebLogic Server - found recommended patch 35476075 ADR FOR WEBLOGIC SERVER 14.1.1.0 CPU OCT 2023
648 | [INFO   ] Oracle WebLogic Server - found recommended patch 35474756 WEBLOGIC SAMPLES SPU 14.1.1.0.230718
649 | [INFO   ] Oracle Coherence - locating latest recommended patches...
650 | [INFO   ] Oracle Coherence - found recommended patch 35778872 Coherence 14.1.1.0 Cumulative Patch 15 (14.1.1.0.15)
651 | [INFO   ] The recommended ADR patch was skipped for the WLS installer, use --patch 35476075 to apply this patch
652 | [INFO   ] Checking for conflicting patches
653 | [INFO   ] No patch conflicts detected
654 | [INFO   ] Could not find key 32720458_14.1.1.0.0 in the cache for patch 32720458
655 | [INFO   ] Downloading patch 32720458...
656 | [INFO   ] Adding patch 32720458_14.1.1.0.0 to cache, path=/root/cache/p32720458_141100_Generic.zip
657 | [INFO   ] Could not find key 35671007_14.1.1.0.0 in the cache for patch 35671007
658 | [INFO   ] Downloading patch 35671007...
659 | [INFO   ] Adding patch 35671007_14.1.1.0.0 to cache, path=/root/cache/p35671007_141100_Generic.zip
660 | [INFO   ] Could not find key 35904051_14.1.1.0.0 in the cache for patch 35904051
661 | [INFO   ] Downloading patch 35904051...
662 | [INFO   ] Adding patch 35904051_14.1.1.0.0 to cache, path=/root/cache/p35904051_141100_Generic.zip
663 | [INFO   ] Could not find key 35474756_14.1.1.0.0 in the cache for patch 35474756
664 | [INFO   ] Downloading patch 35474756...
665 | [INFO   ] Adding patch 35474756_14.1.1.0.0 to cache, path=/root/cache/p35474756_141100_Generic.zip
666 | [INFO   ] Could not find key 35778872_14.1.1.0.0 in the cache for patch 35778872
667 | [INFO   ] Downloading patch 35778872...
668 | [INFO   ] Adding patch 35778872_14.1.1.0.0 to cache, path=/root/cache/p35778872_141100_Generic.zip
669 | [INFO   ] Requesting patch information for patch 28186730
670 | [INFO   ] Failed to get response from patches server, Read timed out, retrying [1/10]
671 | [INFO   ] Could not find key 28186730_13.9.4.2.14 in the cache for patch 28186730
672 | [INFO   ] Downloading patch 28186730...
673 | [SEVERE ] Failed to download and save file /root/cache/p28186730_1394214_Generic.zip from https://updates.oracle.com/Orion/Services/download/p28186730_1394214_Generic.zip?aru=25360527&patch_file=p28186730_1394214_Generic.zip: Read timed out
674 | [SEVERE ] Failed to download and save file /root/cache/p28186730_1394214_Generic.zip from https://updates.oracle.com/Orion/Services/download/p28186730_1394214_Generic.zip?aru=25360527&patch_file=p28186730_1394214_Generic.zip: Read timed out
675 | Something went wrong while creating the Weblogic Docker Image!
`

**Comment by ddsharpe** [comment]
@Tobias-DB I cannot replicate that specific download issue.  But, I have seen some issues with patch downloads timing out for PSUs.  I added retry logic around the download code that should help, assuming this issue is intermittent in nature.  If you are still seeing this issue, can you build and try the main branch of Image Tool to see if it helps resolve your issue?

**Comment by Tobias-DB** [comment]
@ddsharpe Thank you very much for the quick response. Everything is now working :)
