### ISSUE TITLE
Tool still requires JDK even if the base image includes JDK installation

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#50]
Version of WebLogic Image Tool: `1.1.0` 

I'm trying to build an image using `imagetool create` and providing a base image (with `--fromImage`) which already includes an installation of JDK and environment variable `JAVA_HOME` set. But when I run the image creation command, it still throws an error indicating that I need to download the JDK installer and put it in the cache. You can see the command I used and the output:
```
$ imagetool create \
    --docker=docker \
    --fromImage=${BASE_IMAGE_WITH_JDK} \
    --tag=wls:12.2.1.3 \
    --patches ${patch_psu_id},${patch_struts2_id},${patch_jdbc_id}
[2019-07-11 16:51:15] [com.oracle.weblogic.imagetool.cli.menu.ImageOperation] [INFO   ] tmp directory used for docker build context: /tmp/wlsimgbuilder_temp4478144662286527431
[2019-07-11 16:51:18] [com.oracle.weblogic.imagetool.cli.CLIDriver] [SEVERE ] Response code: -1, message: Please download the installer manually and put it in the cache  jdk_8u202
```

The previous command does work when I add the JDK installer to the cache and use the argument `--jdkVersion` to point to it, and the resulting image seems to skip its installation and uses the one provided in the base image.

Is this the expected behaviour?

**Comment by ddsharpe** [comment]
Yes, I saw that bug yesterday when I did testing on a fresh box.  I have the fix staged.  Sorry.
