### ISSUE TITLE
Jre instead of JDK

### ISSUE THREAD

**Issue by senthil13** [oracle/weblogic-image-tool#58]
Hi,
To build a weblogic images only JRE is required( correct me if i am wrong) but this tool allows only with Jdk, is there any possibilities to have only server jre ?  

Thanks

**Comment by jshum2479** [comment]
Yes, you can use server jre, for example 

'''imagetool cache addInstaller --type jdk --path /home/acmeuser/Downloads/server-jre-8u221-linux-x64.tar.gz  --version 8u221'''

then in create you can specify  ```-jdkVersion 8u221```

**Comment by senthil13** [comment]
Thanks, but internally its naming as JDK in the JAVA_HOME variable, Is it ok ?

```
Step 9/41 : ENV JAVA_PKG=${JAVA_PKG:-server-jre-*-linux-x64.tar.gz}     JAVA_HOME=/u01/jdk
 ---> Running in b5823a5e5f95
Removing intermediate container b5823a5e5f95
 ---> a76fd1f48117
Step 10/41 : COPY --chown=oracle:oracle $JAVA_PKG /tmp/delme/
 ---> 4c95f9aed7e8
Step 11/41 : USER oracle
 ---> Running in 39d292a9479a
Removing intermediate container 39d292a9479a
 ---> 6fdc84740359
Step 12/41 : RUN tar xzf /tmp/delme/$JAVA_PKG -C /u01  && mv /u01/jdk* /u01/jdk  && rm -rf /tmp/delme
```

**Comment by jshum2479** [comment]
It's ok, that's the directory name and default convention.
