### ISSUE TITLE
[SEVERE ] Response code: -1, message: user Oracle support credentials do not match

### ISSUE THREAD

**Issue by GerthH** [oracle/weblogic-image-tool#68]
Running imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --user <Oracle Support Email address> --passwordEnv <Oracle Support password> returns: 

[SEVERE ] Response code: -1, message: user Oracle support credentials do not match

The specified credential has download rights for patches to WLS/FMW etc.

How can I prevent this error ?

Regards / Gerth

**Comment by GerthH** [comment]
Weblogic image tool v 1.3.0 (binary).

**Comment by ddsharpe** [comment]
In the command line you posted, you did not provide a userid or a password.  I think we need a better error message here.
Try something like:
 imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --user gerth.h@mycompany.com --passwordEnv MYPASSWORD

where the environment variable MYPASSWORD was set to the password for the userid provided (these are your OTN credentials from Oracle).  The userid is used to download the latest PSU (or patches) from Oracle OTN.

**Comment by GerthH** [comment]
My mistake on copy/paste of end of line. I had stated the password and not an environment variable name... Thank you it seems to resolve the credential issue, but image tool still give me an error.
I have done the  following:

$ imagetool cache addInstaller --type jdk --version 8u221 --path /u01/stage/jdk-8u221-linux-x64.tar.gz
$ imagetool cache addInstaller --type wls --version 12.2.1.3.0 --path /u01/stage/fmw_12.2.1.3.0_infrastructure.jar
$ export MYPASSWORD=<mypassword>
$ imagetool create --tag wls:12.2.1.3.0 --latestPSU --version 12.2.1.3.0 --user <my support email>  --passwordEnv MYPASSWORD
[INFO   ] Temporary directory used for docker build context: /u01/oracledocker/build/wlsimgbuilder_temp8086574971929457281
[SEVERE ] Response code: -1, message: Please download the installer manually and put it in the cache  jdk_8u202

Why dows image tool expect JDK8u202 when I have cached JDK8u221 ?

**Comment by GerthH** [comment]
value of MYPASSWORD is intentionally left out above.

**Comment by GerthH** [comment]
setting environment variable MYPASSWORD and reference it via "--passwordEnv MYPASSWORD

**Comment by ddsharpe** [comment]
I am guessing you figured it out.  Just in case:
The imagetool create command defaults to selecting the 8u201 JDK from the installer cache.  The tool uses a simple key lookup to find it in the .metadata property file.  if you leave off the --jdkVersion command line parameter, imagetool create will look for an installer in the property file with the key jdk_8u201.  But if you specify the command line parameter like "--jdkVersion 8u221", the imagetool create will look for the installer with key equal to "jdk_8u221".  I am open to suggestions for improvement as this cache and key thing for installers has been counterintuitive to more than just you.
