### ISSUE TITLE
XML External Entity Injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [oracle/weblogic-image-tool#75]
https://github.com/oracle/weblogic-image-tool/blob/bf4b8729a66180c23924673beb59b56ae65220c9/imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java#L61-L64
https://github.com/oracle/weblogic-image-tool/blob/bf4b8729a66180c23924673beb59b56ae65220c9/imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java#L169-L172
Using XML parsers configured to not prevent nor limit external entities resolution can expose the parser to an XML External Entities attack

**Comment by ddsharpe** [comment]
Fixed in commit:dba932f124e2050da36f65f2194ed7ebb63a504a
