### ISSUE TITLE
add hook to insert commands in the Dockerfile

### ISSUE THREAD

**Issue by TonyVertenten** [oracle/weblogic-image-tool#78]
in our case we need to add a RUN command in the Dockerfile to remove the simplefan.jar because this causes an error when the Weblogic Deploy Tool is executed. The cause here is because we are using Oracle Database as a Service and the Weblogic Deploy Tool throws an error because it thinks it deploys on a RAC

**Comment by ddsharpe** [comment]
released in 1.5.0
