### ISSUE TITLE
Add retry logic for operation against support site

### ISSUE THREAD

**Issue by jshum2479** [oracle/weblogic-image-tool#83]
We need to add retry logic for any operation aginst ARU, whether it is vadlidating patches, conflict checkers or actual downloading patches.   Occassionally I received cryptic error messages or un-authorized message but retry again works fine.

**Comment by larspusa** [comment]
Got this yesterday when running imagetool, so I guess a retry might help.

[INFO   ] Validated patch 30761841 for release 600000000130803 
[INFO   ] Validated patch 30689820 for release 600000000098910 
[SEVERE ] Response code: -1, message: Read timed out
